### ISSUE TITLE
DME and rudder trim - add OSG Text items

### ISSUE THREAD

**Issue by legoboyvdlp** [legoboyvdlp/A320-family#102]
missing

**Comment by vezza** [comment]
Hi, I've pushed some new code into chrono_dme branch... the following should work, please test for bugs:

DME1 and DME2 indicator's on DDRMI (flightdeck)
chrono (flightdeck)
clock (flightdeck)
ET chrono (flightdeck)
Rudder trim indicator (pedestal)
Unfortunalely my 3D skills are very basic and probably I did something wrong as now the Clock_glare.png doesn't gets shown on the clock... If you know why please tell me or fix it.

**Comment by legoboyvdlp** [comment]
Nice :)

I will check that. It is somewhat important that it shows up...
