### ISSUE TITLE
"autopilot is NAN"

### ISSUE THREAD

**Issue by legoboyvdlp** [legoboyvdlp/A320-family#105]
No more details available. Anyone any ideas? Appears randomly on about 10% of flights.

Spams the console, appears to be harmless but annoying.

**Comment by Octal450** [comment]
I've seen this too, but I couldn't find it. Next time I see it, I'll go through loads of properties generated by the 320 and see if I can find anything.
I "think" it might be from FG? But no confirmed as I never see this when I was testing the MD-11

Kind Regards,
Josh

**Comment by legoboyvdlp** [comment]
For investigation - CFM only.

**Comment by Octal450** [comment]
I haven't been able to reproduce. I'm suspecting the CFM sound files or the CFM FADEC. CFM only is weird though, as the LEAPX/PW neos also use the CFM FADEC, so I'm thinking the CFM56 sound xml?

Josh

**Comment by legoboyvdlp** [comment]
found :D
