### ISSUE TITLE
Feature Request - Copy active flightplan to default routmanager

### ISSUE THREAD

**Issue by merspieler** [legoboyvdlp/A320-family#111]
Copy the currently active flightplan to the default route manager so it shows up on phi and the default maps.

**Comment by Octal450** [comment]
@merspieler I am beginning to working on major improvements to the F-PLN logic and this is planned. Since the route manager and default FMS can be disabled, I don't really think pushing this to it would be a problem

**Comment by legoboyvdlp** [comment]
(wrong emoticon, merspieler ;) )

I tried - didn't go well unfortunately.

**Comment by legoboyvdlp** [comment]
WIP
