### ISSUE TITLE
Bug - Brakes overheat on replay

### ISSUE THREAD

**Issue by merspieler** [legoboyvdlp/A320-family#115]
**Describe the bug**
On replay the brake temperature rises every time the landing is replayed

**To Reproduce**
Steps to reproduce the behaviour:
1. Land
2. Replay the landing multiple times and watch the brake temp

**Expected behaviour**
The brake temp should only rise as high as when it was recoreded.

**Screenshots**

** System (please complete the following information):**
 - OS:
 - FlightGear version:

**Additional context**

**Comment by vezza** [comment]
I fixed this bug, anyway the replay system seems to not work properly... I'm closing this and will open a different issue

**Comment by merspieler** [comment]
Thanks
