### ISSUE TITLE
Bug - Clock: Can't get ET to work

### ISSUE THREAD

**Issue by legoboyvdlp** [legoboyvdlp/A320-family#120]
Does it work properly? 

I set knob to RUN, nothing happens. 

Also seconds display is different to hour / minutes display.

**Comment by vezza** [comment]
It seems to me that it is ok, ET runs/pause/reset as expected (you have to wait at least 60 seconds to see it running or check property tree: instrumentation/clock/... as it shows only hh:mm). The seconds/year display is the center display has a different font size from hour/minutes, see: ![clock](https://user-images.githubusercontent.com/1450066/80299645-4c1c7900-8796-11ea-825d-928c523ec06a.png)

**Comment by legoboyvdlp** [comment]
Thanks!

Sorry - it confused me that it was only minutes, not seconds :)
