### ISSUE TITLE
RMP text looks bad, missing label

### ISSUE THREAD

**Issue by legoboyvdlp** [legoboyvdlp/A320-family#121]
![image](https://user-images.githubusercontent.com/10434911/80229297-21bca580-8648-11ea-8cc4-08ce32f3fd0a.png)

Text is blurry? And missing label?

**Comment by legoboyvdlp** [comment]
Also uv-mapping on pedal adjust (bottom-left)
![image](https://user-images.githubusercontent.com/10434911/80229401-4749af00-8648-11ea-80dc-bef1c00e974b.png)

**Comment by legoboyvdlp** [comment]
Normals fixed on the pedal adjust lever.

**Comment by Octal450** [comment]
That can be fixed by setting the background as JPG not PNG (weird FG thing)
The texture that isn't the labels, I mean
Josh

**Comment by legoboyvdlp** [comment]
rgr, thx.
