### ISSUE TITLE
Bug - Fuel temp is odd

### ISSUE THREAD

**Issue by merspieler** [legoboyvdlp/A320-family#128]
**Describe the bug**
The temp of the Left outer matches the right inner and the left inner matches the right outer.

**To Reproduce**
Steps to reproduce the behaviour:
1. In CRZ take a look at the FUEL ECAM page

**Expected behaviour**
The outer tanks match each other and the inner tanks do,

**Comment by legoboyvdlp** [comment]
yeah... 

don't know whats up
maybe will check positioning in the jsbsim file of the tanks
\_('-')_/

**Comment by Octal450** [comment]
Did you check the JSBsim property if it has the same odd behavior?

Kind Regards,
Josh

**Comment by legoboyvdlp** [comment]
Thanks vezza!
