### ISSUE TITLE
Bug - artifacts on radio panel

### ISSUE THREAD

**Issue by legoboyvdlp** [legoboyvdlp/A320-family#133]
![image](https://user-images.githubusercontent.com/10434911/81472510-64f24900-91f0-11ea-841e-0b7847523857.png)

Look closely at left edge. Only when zoomed out.

**Comment by jelovac** [comment]
Some additional note, pressing on the ON / OFF radio switch with mouse is a little bit tricky. If you do not point exactly on the switch it will rotate the trim wheel instead (pilot side). 

Maybe make the clickable area a little bit bigger or to not rotate the trim wheel?

![radio-switch-issue](https://user-images.githubusercontent.com/3627139/84823864-52550600-b01f-11ea-8c24-41d3d987c311.gif)

**Comment by legoboyvdlp** [comment]
That's quite weird, thanks for the report!
