### ISSUE TITLE
Bug - 

### ISSUE THREAD

**Issue by legoboyvdlp** [legoboyvdlp/A320-family#139]
> Nasal runtime error: undefined symbol: tgt_mach
 5714.44 [ALRT]:nasal     C:\Jenkins\workspace\Windows-nightly\flightgear\src\Scripting\NasalSys.cxx:1330:   at C:/Program Files/FlightGear 2019.2.0/data/Aircraft/A320-family/Models/Instruments/PFD/PFD.nas, line 1309
 5714.44 [ALRT]:nasal     C:\Jenkins\workspace\Windows-nightly\flightgear\src\Scripting\NasalSys.cxx:1335:   called from: C:/Program Files/FlightGear 2019.2.0/data/Aircraft/A320-family/Models/Instruments/PFD/PFD.nas, line 299
 5714.44 [ALRT]:nasal     C:\Jenkins\workspace\Windows-nightly\flightgear\src\Scripting\NasalSys.cxx:1335:   called from: C:/Program Files/FlightGear 2019.2.0/data/Aircraft/A320-family/Models/Instruments/PFD/PFD.nas, line 2683
 5714.70 [ALRT]:nasal     C:\Jenkins\workspace\Windows-nightly\flightgear\src\Scripting\NasalSys.cxx:1312: 

A user is getting this @mattmaring 

I think initializing this variable to nil would avoid the error (totally breaks the PFD). 

However, I am a bit confused why this error is showing up - perhaps a logic error?

**Comment by mattmaring** [comment]
Just reproduced it, comes as a result of triggering mach during approach or decel. Fix will be pushed shortly.

I'm also confused how it was triggered that high up.

**Comment by mattmaring** [comment]
Edit: looking at the full conversation that was the issue. Decel looks to be triggered in the first photo.

**Comment by legoboyvdlp** [comment]
Is this closable now?

**Comment by legoboyvdlp** [comment]
If there's any bug its in my code not yours I think  :) - reported issue has been fixed so will close
