### ISSUE TITLE
Bug - ruder pedals move after starting engines

### ISSUE THREAD

**Issue by legoboyvdlp** [legoboyvdlp/A320-family#143]
Use "Ready to takeoff" and observe rudder pedals after engines start. 

They move!

**Comment by Octal450** [comment]
Weird, ok I'll check this out asap.

Josh

**Comment by Octal450** [comment]
Can't reproduce the rudder pedals moving in a rudder way, only in a brake way. That is intentional, as brakes are applied during the JSBsim "jump-start" as otherwise the plane would roll forward rapidly.

Kind Regards,
Josh
