### ISSUE TITLE
Feature Request - MCDU update

### ISSUE THREAD

**Issue by sylvainar** [legoboyvdlp/A320-family#147]
I don't know if it's normal or it's because i'm not familiar with the MCDU but it seems that I can't delete waypoints after they're added into the route.

Also, is there a way to update definitions of navids into the MCDU? I used approach maps from the SIA which is the french website for that kind of resources, there are some waypoints that can't be found in the system.

Thanks a lot for your answer, i know it's not really a feature request.

**Comment by legoboyvdlp** [comment]
Hi,
To delete waypoints you can enter "CLR" key and then use the line select key beside the one you want to delete.

As for the navaids, yeah I'm working on that right now :)

you can enter already via latitude / longitude

The format is XXYY.Z{N/S} /XXXYY.Z{E/W}
Notice leading zero can be omitted. Not intermediate ones. Only leading ones.
For instance,  5436.2N/322.5E.    { 54 36.2 North, 3 22.5 East }
Or 202.1S/15055.6W    { 2 02.1 South, 150 55.6 West }


You can also enter by place/bearing/distance already (working on improving this). For instance, REDFA/360/10.

**Comment by sylvainar** [comment]
Thanks a lot!
Would there be a way to update navaids directly into flightgear so the whole community would benefit from it?

**Comment by legoboyvdlp** [comment]
No, not at present. They will be updated whenever scenery is updated only, otherwise there could be mismatches (e.g. with ils --> runway).

**Comment by sylvainar** [comment]
Okay thanks for your answers, I'm pretty new in this community and don't really know how things are working in flightgear and where data is coming from.
