### ISSUE TITLE
Bug - trim input

### ISSUE THREAD

**Issue by legoboyvdlp** [legoboyvdlp/A320-family#150]
Trim input should use trim units, not normalized /controls/flight/elevator-trim

This is to avoid rounding causing it to skip from e.g. 0.9 to 1.1 directly, skipping 1.0.

**Comment by legoboyvdlp** [comment]
@Octal450 Do you have any suggestions on this?

**Comment by Octal450** [comment]
I did that for you already.
Surface position: /fdm/jsbsim/hydraulics/elevator-trim/final-deg
Cmd Deg from wheel: /fdm/jsbsim/hydraulics/elevator-trim/cmd-deg

Surface position shows the ACTUAL position after hydraulics. Cmd Deg shows what the trim wheel is commanding to the stab.

Kind Regards,
Josh

**Comment by legoboyvdlp** [comment]
However, the _input_ on the trim wheel itself doesn't seem good -- it isn't possible to command +1.0 for instance, only +0.9 or +1.1.

**Comment by Octal450** [comment]
You could cut the amount if slews on click in half.
Completely killing controls flight elevator trim would be extremely problematic.

Alternatively I could design a custom function that slews it by the .1 degree if you wish.

Kind Regards,
Josh

**Comment by legoboyvdlp** [comment]
That would be good :+1:

**Comment by Octal450** [comment]
Which one? :D

**Comment by legoboyvdlp** [comment]
.1 deg! Then it will be good :)

**Comment by Octal450** [comment]
Oke. I'll do that asap.
