### ISSUE TITLE
Feature request - Move external ground stuff to ground services menu

### ISSUE THREAD

**Issue by jelovac** [legoboyvdlp/A320-family#151]
**Is your feature request related to a problem or missing feature? Please describe.**

Currently external power units, external air conditioning supply and landing gear choke entries are located under Aircraft configuration. It seems logical to me that they should be located under Ground services menu.

**Comment by legoboyvdlp** [comment]
Good idea, thanks.

**Comment by merspieler** [comment]
When doing that, we should consider, having just one box for the chocks, instead of 3 for each bogey

**Comment by jelovac** [comment]
Experimented a little bit today with the menus:

![a320-ground-service-menu-changes](https://user-images.githubusercontent.com/3627139/84694413-73e3be00-af49-11ea-8cd3-d69a9a02e084.png)

**Comment by jelovac** [comment]
Reordered a little bit, looks better in my opinion.

![updated-ground-services](https://user-images.githubusercontent.com/3627139/84705779-350b3380-af5c-11ea-95a2-4fc032bb8e55.png)

**Comment by merspieler** [comment]
Looks good... only the font is weird.

I'd make it just one Checkbox for all chocks.

And note, that the APU oil stuff will be moved to the WIP maintenance dialog.

**Comment by jelovac** [comment]
> 
> 
> Looks good... only the font is weird.
> 
> I'd make it just one Checkbox for all chocks.
> 
> And note, that the APU oil stuff will be moved to the WIP maintenance dialog.

I merged  main left and right gear chokes under the single checkbox, nose choke is still separated.

Was not sure if we should merge it as well, currently it doesn't occupy vertical space since they are aligned side by side.

As for the fonts, it's because of my selected GUI style. Unfortunately I own an ATI card R390 which has issues with the standard menu style (menu elements invisible).

**Comment by legoboyvdlp** [comment]
Thanks :)
