### ISSUE TITLE
Bug - Auto throttle doesn't respect indicated speed above FL300

### ISSUE THREAD

**Issue by jelovac** [legoboyvdlp/A320-family#152]
**Describe the bug**

Not entirely sure if this is a bug or not, but when I get above FL300 and the max speed limit on PFD gets reduced from 30x kts to 280kts the specified air speed is not respected and I constantly get over speed warning.

At that point I have to disengage the auto throttle and set it manually.

I am guessing that this has something to do with simulated atmospheric pressure, however not sure if it is an actual bug or not.

Same issue happens when speed is defined by MCDU PERF.

** System (please complete the following information):**
 - OS: Windows 10
 - FlightGear version: 2020.1.2

**Comment by legoboyvdlp** [comment]
I do not understand. When does the max speed limit reduce? And can you show a screenshot when it does not respect your speed? Are you sure you are in climb thrust and not in TOGA LK?

**Comment by jelovac** [comment]
Max speed limit reduces when I reach certain flight level above 30k ft. This happens when I am both in climb mode and cruise mode above that flight level.

I will make a video tomorrow.

Keep in mind that I am not a real pilot so I might lack some background knowledge and I am doing something wrong.

The best way is to show you, so will upload a video tomorrow along with some screenshots.

**Comment by legoboyvdlp** [comment]
Thanks!

**Comment by merspieler** [comment]
If I understand it right, he refers to the point where MMO limits max KIAS rather than VMO

**Comment by jelovac** [comment]
Hi,

I was not able to reproduce the issue anymore. My settings were similar like on the screenshot bellow, however auto throttle wasn't respecting the speed set either by onboard computer (MCDU PERF mode) or by me manually.

![fgfs-20200614172018](https://user-images.githubusercontent.com/3627139/84601174-aa083b80-ae7e-11ea-8848-40699eacc46b.png)

It is highly possible that I miss configured something so I am closing this issue because I won't be able to test this properly in the upcoming weeks.
