### ISSUE TITLE
Bug - Wind page issues/future improvements

### ISSUE THREAD

**Issue by mattmaring** [legoboyvdlp/A320-family#159]
* Winds do not reset correctly on after-landing INIT reset, causes nasal error (line 125 CLB wind)  (done)
* Properly clear winds with arrival changes (done)
* GRND wind transferred to approach page (done)
* ALT wind sometimes fails to display after entry (done)
* Allow 0s in the wind values (done)
* History wind not implemented (done)
* Add stars to insert/update (done)
* Propagate cruise winds (won't fix - until F-PLN is done)

**Comment by legoboyvdlp** [comment]
Another nasal one: I think after reset also
Nasal runtime error: non-objects have no members
 2998.31 [ALRT]:nasal     C:\Jenkins\workspace\Windows-release\flightgear\src\Scripting\NasalSys.cxx:1331:   at C:/Users/Stefan/Documents/doc/FlightGear/Aircraft/A320-family/Nasal/FMGC/winds.nas, line 121
 2998.31 [ALRT]:nasal     C:\Jenkins\workspace\Windows-release\flightgear\src\Scripting\NasalSys.cxx:1336:   called from: C:/Users/Stefan/Documents/doc/FlightGear/Aircraft/A320-family/Nasal/FMGC/winds.nas, line 182
 2998.31 [ALRT]:nasal     C:\Jenkins\workspace\Windows-release\flightgear\src\Scripting\NasalSys.cxx:1336:   called from: C:/Users/Stefan/Documents/doc/FlightGear/Aircraft/A320-family/Nasal/FMGC/flightplan.nas, line 99
 2998.31 [ALRT]:nasal     C:\Jenkins\workspace\Windows-release\flightgear\src\Scripting\NasalSys.cxx:1336:   called from: C:/Users/Stefan/Documents/doc/FlightGear/Aircraft/A320-family/Nasal/MCDU/ARRIVAL.nas, line 649
 2998.31 [ALRT]:nasal     C:\Jenkins\workspace\Windows-release\flightgear\src\Scripting\NasalSys.cxx:1336:   called from: C:/Users/Stefan/Documents/doc/FlightGear/Aircraft/A320-family/Nasal/MCDU/ARRIVAL.nas, line 770
 2998.31 [ALRT]:nasal     C:\Jenkins\workspace\Windows-release\flightgear\src\Scripting\NasalSys.cxx:1336:   called from: C:/Users/Stefan/Documents/doc/FlightGear/Aircraft/A320-family/Nasal/MCDU/MCDU.nas, line 421
