### ISSUE TITLE
Bug - Fire indications not lit/bright enough

### ISSUE THREAD

**Issue by merspieler** [legoboyvdlp/A320-family#16]
**Describe the bug**
The Fire PB and the fire indication next to the ENG master SW are not lit or noght bright enough

**To Reproduce**
1. Press ENG fire test button
2.  Observer indications

**Expected behaviour**
Clearly visible indications

**Comment by L1011H** [comment]
Fixed on the OH(CaptB)

[OHpanel.zip](https://github.com/legoboyvdlp/A320-family/files/3750449/OHpanel.zip)

**Comment by merspieler** [comment]
Thanks... @L1011H 

Do you know as well, how to fix the indications on the pedestal, near the eng master switches?

Oh... and don't be shy... you can do the changes your self and open a PR next time ;-)

**Comment by L1011H** [comment]
@merspieler 

I don't know yet, but I will look into it. Also, the fire buttons on the overhead should lit up with the annunciator light switch set to TEST which they are not. I'll look into both of these issues.

**Comment by L1011H** [comment]
Pedestal issue solved, will upload tomorrow(too sleepy now)

**Comment by L1011H** [comment]
Unable to upload here today. "Something went really wrong, and we can't process that file" Will try later?

**Comment by L1011H** [comment]
Pedestal Fire fix:
[pedestal_fix.zip](https://github.com/legoboyvdlp/A320-family/files/3756051/pedestal_fix.zip)

**Comment by legoboyvdlp** [comment]
Hi,
Thank you CaptB. I will add you to the repository as a collaborator now.

To confirm these changes do not modify the 3D, only the .xml?

**Comment by L1011H** [comment]
> Thank you CaptB. I will add you to the repository as a collaborator now.

Thank you!

> To confirm these changes do not modify the 3D, only the .xml?

Yes only XML, no 3D was involved. Also I have completely fixed the overhead issue(Now ENG/APU FIRE will lit up on a fire test or annunciator test) will push that one to the appropriate branch shortly instead of attaching here.

**Comment by legoboyvdlp** [comment]
👍
