### ISSUE TITLE
Feature Request - document simulated aircraft specs

### ISSUE THREAD

**Issue by jelovac** [legoboyvdlp/A320-family#160]
I am often using SimBrief.com for flight plan generation in order to make my flight simulation experience more realistic.

In SimBrief you can define your aircraft details in order to have flight plan custom tailored for your aircraft.

It would be nice to have some details about simulated aircraft.

So far what I was able to extract is the following information:

- Weights
- Aircraft type
- Engines (from MCDU)

The rest was googling for A320 specs on the internet, SimBrief A320 specs for XPlane and guessing.

Attaching an example how it looks like currently in SimBrief:

![Annotation 2020-06-24 210521](https://user-images.githubusercontent.com/3627139/85616745-76879700-b65e-11ea-9c43-8c1e240f800f.png)

**Comment by merspieler** [comment]
I agree, but we should wait, until all are actually correct in the plane, not that we have to change it.

**Comment by legoboyvdlp** [comment]
For all these details -- registration and fin number is custom each time. Surely this is something that each individual user should do for themselves, with the options they want?

Certainly weights are custom tailored to each aircraft.

I am not sure what I understand you want me / anyone else to do here?

**Comment by jelovac** [comment]
> Certainly weights are custom tailored to each aircraft.

Unless I am missing something all of these weights are constants in a simulator.

For example:

- Maximum Take-Off Weight (MTOW) is a constant
- Maximum Landing Weight (MLW) is a constant
- Maximum Zero Fuel Weight (MZFW) is a constant
- Maximum Fuel Capacity is a constant
- Empty Weight (OEW) is a constant since we cannot currently modify it withing the flightgear unless I am missing something

My understanding is that currently when you go to the Fuel and payload settings what we are setting is the actual payload on top of OEW, basically passengers count (in weight) and cargo.

> For all these details -- registration and fin number is custom each time. Surely this is something that each individual user should do for themselves, with the options they want?

Of course, everything which is not a constant should be ignored.

Also don't focus too much on SimBrief example, it's just an example. My main point was that we should have information regarding the simulated aircraft's which could actually be useful but is specific to the simulator.

The rest we can obtain from Airbus documentation.

**Comment by legoboyvdlp** [comment]
Correct. The weights of each variant however are different. A specific weight variant is taken from the EASA Type Data Certificate Sheet. The MTOW, MLW, and so on are different for each variant. Empty weight is also different, since each engine has its own unique weight.

What information would you like, I would be glad to provide what I can?

**Comment by jelovac** [comment]
> Correct. The weights of each variant however are different. A specific weight variant is taken from the EASA Type Data Certificate Sheet. The MTOW, MLW, and so on are different for each variant. Empty weight is also different, since each engine has its own unique weight.
> 
> What information would you like, I would be glad to provide what I can?

Thanks, for now I am good.

MTOW, MLW, MZFW - are already available from the UI.

OEW value I got by removing all the fuel and payload from the "Fuel and Payload Settings" dialog and looking at the gross weight.

Maximum fuel qty I got by sliding all the fuel settings to the maximum and looking at the qty in "Fuel and Payload Settings". The other way was to look at the A320-200-IAE.xml and sum all the "capacity" values for fuel tanks.

**Comment by legoboyvdlp** [comment]
Do note all variants have different fuel capacity :)

Also the weights will be changing, there are some fuel + payload improvements coming.
