### ISSUE TITLE
Feature Request - Replace/Remove splashscreens showing the old model

### ISSUE THREAD

**Issue by merspieler** [legoboyvdlp/A320-family#167]
Since we've got the new model, we should remove/replace all splash screens, showing the old model

As well... do we really need 6 splash-screens?

3 Should be enough...
* One Cockpit
* One Wing
* One outside

**Comment by legoboyvdlp** [comment]
Cockpit doesn't need changed but definitely wing + outside!

**Comment by legoboyvdlp** [comment]
@merspieler Any chance you could provide these from the new model -- how is your screen resolution?
Mine is too low for good screenshots.

Optional... photoscenery :) :) :)

**Comment by merspieler** [comment]
Sure.

1920x1080 (... or ultra wide, 5760x1080 :-P) 

How about my SOTM for the wing view?
![](https://seafile.merspieler.tk/f/fd65b09dc14549e7957b/?dl=1)

And any location for the outside view?
... Which livery?

**Comment by legoboyvdlp** [comment]
Of the two I prefer Swiss myself... but ofc in good lighting conditions. FG renderer being somewhat odd, it probably looks best in good weather conditions. Maybe external view could be on the ground at a nicely modelled airport, e.g. Boston or Portland (Maine) in the USA?

**Comment by merspieler** [comment]
I'll play around with KBOS...

**Comment by legoboyvdlp** [comment]
Done
