### ISSUE TITLE
Feature Request - Rudder moved by wind, when on ground

### ISSUE THREAD

**Issue by merspieler** [legoboyvdlp/A320-family#168]
Just a nice to have...
The rudder is moved by the wind, when on ground and the HYD systems are not pressurized.

**Comment by legoboyvdlp** [comment]
Are you sure about this -- the centering spring in the feel unit should prevent this, unless the wind is rather strong.

**Comment by merspieler** [comment]
https://www.youtube.com/watch?v=7sAmkqBZ0lw

**Comment by legoboyvdlp** [comment]
About 2/3 of images show that it is neutral.
![image](https://user-images.githubusercontent.com/10434911/87853523-b3b01380-c902-11ea-983c-23909cef5c36.png)

![image](https://user-images.githubusercontent.com/10434911/87853528-c0cd0280-c902-11ea-9786-a46f582cdc99.png)

(For instance ^ above, obviously a thunderstorm, so rather stronger winds!)

I suppose the wind is sometimes strong enough to overcome the spring...

**Comment by legoboyvdlp** [comment]
Or else, the yellow pump is on in those images, for cargo door operations, of course...
