### ISSUE TITLE
Bug - constant error message with auto-coordination enabled

### ISSUE THREAD

**Issue by Honu4** [legoboyvdlp/A320-family#172]
Thereʻs a constant stream of the same error message. In the past it would only appear once.

Steps to reproduce the behaviour:
1. enable auto-coordination in launcher settings
2. Start flight

**Screenshots**
<img width="509" alt="Screen Shot 2020-07-19 at 4 24 02 PM" src="https://user-images.githubusercontent.com/67807217/87893681-496ba180-c9dc-11ea-879a-f1992526066f.png">
![fgfs-20200720021854](https://user-images.githubusercontent.com/67807217/87893520-deba6600-c9db-11ea-85ae-5a6d083814c2.png)

**System:**
 - OS: MacOS 10.15.6
 - FlightGear version: 2020.2.1 nightly

**Comment by legoboyvdlp** [comment]
Thanks.
