### ISSUE TITLE
Bug - Hydraulics ECAM page shows misleading alerts

### ISSUE THREAD

**Issue by MiSKLaCH** [legoboyvdlp/A320-family#181]
### General
----
I am submitting a: (select one) 
* [x] Bug report
* [ ] Feature request

### Details
----
#### Expected Behavior (bug reports)
In the hydraulics ECAM page shouldn't be displayed warnings/alerts when everything is fine.

#### Current Behavior (if applicable)
Despite engines running or not running, hydraulics ECAM page keeps showing:
- OVHT
- LO AIR PRESS

(see https://imgur.com/a/orl5GpY for screenshots of both running and not running engines)

#### Requested Behavior  (feature requests)
Show alerts only in case of real hydraulics failures.

#### Possible Solution (if applicable)
Review last updates, something has been changed in the last commits and now this happens.

#### Steps to Reproduce (bug reports)
1. load the aircraft
2. connect GPU
3. after self test check hydraulics ECAM page (it shows the alerts described above)
4. power on the engines
5. check hydraulics ECAM page (shows pressure on G/B/Y but still alerts)

**Comment by merspieler** [comment]
@legoboyvdlp you've changed something on the ecam recently. any chance, you've missed that?

@MiSKLaCH the images don't show here. Please upload them directly to github in future.

**Comment by MiSKLaCH** [comment]
Engines not running:
![hyd_bug](https://user-images.githubusercontent.com/15834441/94673521-22ecaf80-0317-11eb-9af0-bf777b01c570.png)

Engines running:
![hyd_bug_engines_on](https://user-images.githubusercontent.com/15834441/94673577-3a2b9d00-0317-11eb-8c25-d68c402c7083.png)

**Comment by merspieler** [comment]
Thanks, there's more wrong than just the LO AIR PRESS and OVHT...
Valves are showing weird stuff too.

**Comment by legoboyvdlp** [comment]
It would have been helpful if you had posted the Nasal runtime error.

It did not happen here, I checked each page one by one.

Can you please post it?

Thanks 👍

**Comment by MiSKLaCH** [comment]
I see this in the Nasal console, hope it helps (note that even the clock in the lower part is screwed, UTC time was definetely not 00 H 00)
![nasal_console](https://user-images.githubusercontent.com/15834441/94699067-378e6f00-033a-11eb-8a3d-977a11d14e5f.png)

Edit: pretty much all values are weird, UTC time, GW, TAT and SAT are all completely different from the other pages. Values are NOT updated, those shown are the SVG defaults (see below)
![hyd_svg](https://user-images.githubusercontent.com/15834441/94703097-c7361c80-033e-11eb-8d3a-90af68d4731f.png)

**Comment by legoboyvdlp** [comment]
Thanks, I've corrected it now. There was a typo, where it would seemingly refer to a variable I created in another, unrelated file. However, it would work without giving an error message - when I removed the variable (_after_ checking the displays) it then broke. I've (re-)checked all other displays as well. All seems to be working now!
