### ISSUE TITLE
Feature Request - realistic behaviour of ADIRS alignment process

### ISSUE THREAD

**Issue by MiSKLaCH** [legoboyvdlp/A320-family#182]
**Is your feature request related to a problem or missing feature? Please describe.**
Even though this aircraft is pretty well modeled and it is almost payware quality, there are some things which are yet to be fixed or implemented from scratch. I hope the following in particular will not be too hard to make. ;)

The ADIRU splits in two separate units which are respectively:

- AD or Air Data unit, which provides informations about Airspeed, Altitude, Angle of Attack, Temperature, Overspeed and Mach numbers. This informations are used mostly by PFD, Primary Flight Display.
- IRU or Inertial Reference Unit, which is in charge with Ground Speed, Aircraft Position, Attitude, Flight Path Vector (or FPV), Heading, Acceleration and Track provides informations to both the PFD and ND, or Navigation Display.

So, when the IRS isn't aligned the ND cannot display informations like the map (both NAV / ARC modes) because it relies on the IRS unit datas but it can still show informations in modes where datas are provided by radio navigation systems, like VOR and ILS modes. It can provide datas in the PLAN mode too because such informations come from the MCDU flight plan, if any.

In the A320-family aircrafts, as soon as the systems are powered up and the displays become available, the ND is almost instantly displaying the map (even with ADIRS switches in the OFF position) while the PFD has to wait for the whole IRS alignment process to finish to display informations, and this is not what is happening with the real aircraft.

**Describe the solution you'd like**
After the aircraft is powered on by APU or GPU and the displays perform their self test, the PFDs and NDs show no informations (red screens).

![image](https://user-images.githubusercontent.com/15834441/95353380-7fc20a00-08c3-11eb-855f-6a66e2cffc13.png)

Once the ADIRS alignment process is started (ADIRS 1, 2 and 3 switches to NAV in the overhead panel / IRS INIT in MCDU INIT-A page) the PFD shows informations well before the ND, which will display red HDG / MAP NOT AVAIL / GPS PRIMARY LOST messages until the IRS will be eventually aligned. 

![image](https://user-images.githubusercontent.com/15834441/95353353-789afc00-08c3-11eb-9c0f-d9a80f451a4f.png)

**Additional context**
More detailed informations are available on YouTube and other media, such as the following:
- https://youtu.be/Mo7A3CuVb8g
- https://youtu.be/uqKeSO6msDk
- https://youtu.be/cbbThW09imU

**Comment by legoboyvdlp** [comment]
Thanks,

This is already simulated internally - however, the ND doesn't yet have the drawings. Actually, if you'd like to help out on this, drawing the red "map not AVAIL" would help! :) 

I wasn't aware of the difference between the PFD and ND - I suppose attitude is available sooner than the position?

**Comment by MiSKLaCH** [comment]
I'm not used to SVG drawing but I'll give it a try for sure :)
I guess you already know this site: http://www.a320dp.com/A320_DP/menu.html

Just in case you don't, It's an overwhelming source of informations about A320 systems.
Here is the section about the panels: http://www.a320dp.com/A320_DP/panels.html

You guys are doing a GREAT job, hope I can help somehow.

**Comment by merspieler** [comment]
Think, I've seen that.
These sites are not guaranteed to be 100% accurate so we usually use only pictures of real aircraft and the FCOM (Flight Crew Operational Manual) as reference.

At one point, any one of us had any lack of experience for what we wanted to do... creating an aircraft always involves learning.

If you need any help or guidance, let us know.

**Comment by MiSKLaCH** [comment]
Here it is. I don't even know if I placed the objects correctly.
What I've done is to create a new layer called UNAVAIL with the graphics of NAV and ARC modes in "unavailable state".
Let me know in case I screwed everything up, that's my first time with SVGs.
 
[airbusND.zip](https://github.com/legoboyvdlp/A320-family/files/5348720/airbusND.zip)

**Comment by merspieler** [comment]
Looks good...

You had a few twists...
* The naming of ARC vs NAV was flipped
* The outer ARC wasn't in the group

Apart from that, the only thing I had to change, was to rename the GPS PRIMARY LOST as there are more possible message (which are as well not yet implemented)... tho that you probably didn't have on your radar yet.

Loading it in flightgear gives me an error tho:
```
   12.28 [ALRT]:nasal      parsesvg: parse XML failed [path='/games/.fgfs/Aircraft/A320-family/Models/Instruments/ND/canvas/res/airbusND.svg']
   12.28 [INFO]:nasal      cannot change immutable string:
 at /games/fgdata/Nasal/canvas/svg.nas, line 428
   12.28 [INFO]:nasal        called from: /games/fgdata/Nasal/canvas/svg.nas, line 748
```

**Comment by MiSKLaCH** [comment]
There is a new version in my previous comment, I noticed I forgot the outer arc (and added it).
I'll try to look into such error and will let you know (hopefully).

**Comment by MiSKLaCH** [comment]
Oopsie... wrong button, my bad (reopened).

**Comment by merspieler** [comment]
The error seems to come from a rectangle object, you've added...

**Comment by MiSKLaCH** [comment]
Strange thing there is only one error! :)
The rectangle could be the one surrounding the GPS PRIMARY LOST, it's the only rectangle added.

**Comment by merspieler** [comment]
remove it and see if it works ;-)

**Comment by MiSKLaCH** [comment]
Removed but no luck... trying to solve the issue. :( 
I'm doing some tests, will let you know asap.

**Comment by MiSKLaCH** [comment]
Managed to fix it, it seems it was a damn font issue.
Let me know in case something is broken.

[airbusND.zip](https://github.com/legoboyvdlp/A320-family/files/5348720/airbusND.zip)

**Comment by merspieler** [comment]
Looks good.

Next would be the logic... do you want to give it a try with our help?

**Comment by MiSKLaCH** [comment]
Why not, I'm glad to help this project :)

**Comment by merspieler** [comment]
Great.

I've never touched the ND Code my self so it might take me some time, to point you in the right direction or @legoboyvdlp might help out with that.

If you like to contribute more, I'd highly recommend, that you take a look at git (install it on your PC) so you can commit your changes and then create a pull request, when you think, your changes are ready for being merged.  
If you need any assistance, let me know.

**Comment by legoboyvdlp** [comment]
The ND is ... complicated... I guess it would mean adding code to Instruments/ND/canvas/ND.nas. 

Line 182 and 202, there are two objects, each with getKeys() and update().

Inside update() it should work to update the hiding / showing of the error message.

essentially, you want a condition similar to this:

`if (systems.ADIRS.ADIRunits[0].aligned == 1 or (systems.ADIRS.ADIRunits[2].aligned == 1 and att_switch.getValue() == -1)) {`

That means: unit 1 is aligned (zero-based index) _or_ unit 3 is aligned and attitude switching is on CAPT.

The R/HS would have unit[1] aligned _or_ unit 3 aligned and attitude switching on FO i.e. +1.

**Comment by MiSKLaCH** [comment]
@merspieler I already have git on my Linux PC but I guess I should learn other arguments apart from "clone", "pull" and "whatchanged" :smile: 
I'll give it a look, and thank you @legoboyvdlp for the hints! :wink:

**Comment by merspieler** [comment]
Then you've got the basics already.

For `git pull` there's the `--rebase` argument which you should use, if you pulling on a branch where you have some work committed but not yet pushed (to avoid unnecessary merges).

`git branch` and `git remote` are worth a look when you start handling multiple branches and repos, both are quite stright forward tho.

`git stash` is another thing that I use frequently.

Then you obviously need `git add`, `git commit` and `git push`.

... I've never heard of `whatchanged`... it's new to me :D 

[These](http://sethrobertson.github.io/GitBestPractices/) are the best practice, I try to follow... if you need a lecture to read in the evening ;-)

**Comment by MiSKLaCH** [comment]
Ok, I gave it a good look and ... gave up! :disappointed: It's just waaay too complex for my poor skills.
I hope some day the drawings I made will be somewhat useful to you.

**Comment by merspieler** [comment]
There for, that you've got no clue, you've asked very little questions... :P

That's fine....

@legoboyvdlp do you mind, adding it?

**Comment by legoboyvdlp** [comment]
Implemented this. The IR part will be redone later with the rest of the ADIRS. Thanks!
