### ISSUE TITLE
Bug - Chrono doesn't show hours

### ISSUE THREAD

**Issue by merspieler** [legoboyvdlp/A320-family#183]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:
1. Start chrono
2. Wait 100 minutes.
3. Observe, starting over from 00:00

**Expected behaviour**
Switch to showing hours and minutes

**Screenshots**

**System (please complete the following information):**
 - OS: 
 - FlightGear version: 

**Additional context**

**Comment by legoboyvdlp** [comment]
Edit - nvm, I wonder did I break it last change.

**Comment by legoboyvdlp** [comment]
![image](https://user-images.githubusercontent.com/10434911/95495634-99348600-0997-11eb-8f3b-4285e9ee4aea.png)

**Comment by merspieler** [comment]
I've confused it with the chrono on the ND:
(9) Chronometer Indication (white)
These numbers appear when the onside chronometer is started.
They display the elapsed time.
The indication is in minutes and seconds from 0 to 59 min 59 s, and in hours and minutes from 1 h
to 99 h 59 min (Seconds are not displayed beyond 59 min 59 s).


... and the ET
