### ISSUE TITLE
Feature Request - WingFlex

### ISSUE THREAD

**Issue by mohamedaissa** [legoboyvdlp/A320-family#186]

**Comment by merspieler** [comment]
Please see: https://github.com/legoboyvdlp/A320-family/issues/30

... and you can edit your issue ;-)

**Comment by mohamedaissa** [comment]
why please ?

**Comment by merspieler** [comment]
because you need cuts in the model. This would result in ugly seams and complicates the animations a good bit.

Maybe in future, when there's a well working vertex shader, we could add it.

**Comment by mohamedaissa** [comment]
there a wiki article named Wingflex shader wich is a technic to add wingflex without cutting the wing
here's the link :[wiki.flightgear.org/Wingflex_Shader](url)

**Comment by merspieler** [comment]
Okay, last time I've checked, it supported only the organic mode...

This has changed now.

Would you like to give it a try, implementing this on the A320?

We'd help you, if you'd like to do it.

**Comment by mohamedaissa** [comment]
Ok i'll try i need the Wing objects
The object type: rotation or normal
and please the Wingflexer-params
it may take some weeks

**Comment by merspieler** [comment]
Wing objects:
* Wings
* SpoilerR1 through R5 and L1 through L5
* WingtipFence
* navglass
* nawglass.sharklet
* Sharklet
* FlapR1 (R2, L1 and L2)
* EngineFairingR (L)
* FairingR1 through R3, same for L
* AileronR (L)
* SlatR1 (R2, L1, L2)

For the animation, please take a look at the current animations.

I don't have the params either, so you've got to figure that out.

**Comment by mohamedaissa** [comment]
thanks i think i have the Wingflex params from an older version (the launcher one)

**Comment by mohamedaissa** [comment]
for the "Fairing" is it considered as a flap
same question for the Slats 
thanks

**Comment by merspieler** [comment]
I've taken the object names from the 3D branch.. https://github.com/legoboyvdlp/A320-family/tree/3D

The fairing is part of the flap mechanism..

**Comment by mohamedaissa** [comment]
thank you very much i might finish the wingflex aniamtion this weekend
sorry for bothering you so much

**Comment by merspieler** [comment]
no worries, we've all started like that ;-)

**Comment by mohamedaissa** [comment]
ok so is did some test and it worked i'll just fix some bugs and add the slats and the fairing
i will be ready on the next friday at latest because of school

**Comment by merspieler** [comment]
take your time, no need to hurry.

**Comment by mohamedaissa** [comment]
so i have i problem i animated almost everything but i can't animate the actual wing 
help please
thanks

**Comment by merspieler** [comment]
could you please fork this repo and push your changes to it so I can take a look

**Comment by mohamedaissa** [comment]
how please ?

**Comment by legoboyvdlp** [comment]
I see you didnt mention your harassment of four individual people leading to the ban you are so upset about...

**Comment by mohamedaissa** [comment]
let me alone i'm only 13 and i'm in depression because of you. i quitted everything
stop now please

**Comment by merspieler** [comment]
what ever you want

**Comment by mohamedaissa** [comment]
i'm sorry for that merspieler
maybe i'll do it.

**Comment by mohamedaissa** [comment]
i just need the wing object name

**Comment by merspieler** [comment]
See my previous message...
> Wing objects:
> 
>     * Wings
> 
>     * SpoilerR1 through R5 and L1 through L5
> 
>     * WingtipFence
> 
>     * navglass
> 
>     * nawglass.sharklet
> 
>     * Sharklet
> 
>     * FlapR1 (R2, L1 and L2)
> 
>     * EngineFairingR (L)
> 
>     * FairingR1 through R3, same for L
> 
>     * AileronR (L)
> 
>     * SlatR1 (R2, L1, L2)
> 
> 
> For the animation, please take a look at the current animations.
> 
> I don't have the params either, so you've got to figure that out.

**Comment by mohamedaissa** [comment]
thanks
