### ISSUE TITLE
Bug - Retrieving Flightplan from Simbrief fails

### ISSUE THREAD

**Issue by Castingfotograf** [legoboyvdlp/A320-family#188]
**Describe the bug**
Unable to retreive Flightplan Data from Simbrief (worked in previous version)

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'MCDU - INIT Page'
2. Click on 'Retreive'
4. See error "Fatal Error. non-objects have no member

**Expected behaviour**
After Confirming this message. Flightgear crashes

**Screenshots**

**System (please complete the following information):**
 - OS: Windows 10 pro current Version /10/2020)
 - FlightGear version: 2020.1.3

**Additional context**

**Comment by legoboyvdlp** [comment]
Sorry but I need to know what object does not have a member. Can you attach the full log please?

**Comment by Castingfotograf** [comment]
Can you tell me, where to find this log file?-- Peter Schönamsgruber  -  en routeAm 16.10.20, 21:09 schrieb legoboyvdlp <notifications@github.com>:

   
  Sorry but I need to know what object does not have a member. Can you attach the full log please?

**Comment by legoboyvdlp** [comment]
It should be at C:\Users\user name\AppData\Roaming\flightgear.org\fgfs.log

Thanks!

**Comment by Castingfotograf** [comment]
Just sent  you the log file via an other Emailer. I hope, it reached you.Tgank you for the great work!-- Peter Schönamsgruber  -  en routeAm 16.10.20, 21:12 schrieb legoboyvdlp <notifications@github.com>:

   
  It should be at C:\Users\user name\AppData\Roaming\flightgear.org\fgfs.log 
  Thanks!

**Comment by legoboyvdlp** [comment]
Unfortunately it hasn't yet :(

**Comment by legoboyvdlp** [comment]
Maybe send it directly to <legoboyvdlp @ gmail . com>?

**Comment by legoboyvdlp** [comment]
Closed per private communication, thx for the report :+1:
