### ISSUE TITLE
Feature Request - Wind request

### ISSUE THREAD

**Issue by mattmaring** [legoboyvdlp/A320-family#189]
Pull wind data from SimBrief

**Comment by valtsu41** [comment]
Could this be supported with custom weather configurations too?

**Comment by mattmaring** [comment]
Perhaps in the future, my current implementation is just a simple pull from SimBrief (analogous to the INIT request).

I definitely see that being a useful feature for those not flying online. Probably will come later once I finish on the flightplan/fuel work.

**Comment by mattmaring** [comment]
Done (in fuel-climb-descent)
