### ISSUE TITLE
Feature Request - Toggle flightdeck headset on/off

### ISSUE THREAD

**Issue by L1011H** [legoboyvdlp/A320-family#19]
Make the headset in the flightdeck clickable so that the headset can be switched on/off in order to have a non obstructed view.

**Comment by L1011H** [comment]
This was a small thing that annoyed me. A click on the Audio Control's Panel's  body will now toggle the headset object on/off.

There's a new property at /controls/audio/headset-toggle please let me know if there's a more suitable place for it.

**Comment by legoboyvdlp** [comment]
That sounds fair enough; alternately you could click the speaker on the left hand side of the PFD (easier to avoid accidental clicks)? I have no strong feelings as to which.

**Comment by L1011H** [comment]
There are probably better places for that in the flightdeck and the speaker would be a good choice, however none of these are separate objects. It's not a problem to make it one but I don't want to get in Thorsten's way here so I preferred to make it so that there is no need for any changes to the flightdeck 3D model.

We can change the toggle object in the future should we get something ready for that from Thorsten.

**Comment by L1011H** [comment]
[headset-toggle.zip](https://github.com/legoboyvdlp/A320-family/files/3766008/headset-toggle.zip)

**Comment by legoboyvdlp** [comment]
Feel free to commit directly if you wish, if not I'll do it later on this week ;)

**Comment by L1011H** [comment]
Sure I'll do it. Just to confirm, direct to master?

**Comment by legoboyvdlp** [comment]
Yep, absolutely.
