### ISSUE TITLE
Bug - missing file in the installation procedere

### ISSUE THREAD

**Issue by didi31434** [legoboyvdlp/A320-family#190]
**Describe the bug**
During the installation a issue report occoured.
Documentet in the sreenshot

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**
a working A 320 simulation 

**Screenshots**
![Unbenannt](https://user-images.githubusercontent.com/73137663/96504129-9158c980-1254-11eb-8a63-05b4669144e9.PNG)

**System (please complete the following information):**
 - OS: Win 10
 - FlightGear version: 2020.1.3

**Additional context: N/A

**Comment by legoboyvdlp** [comment]
Please read the installation instructions.

**Comment by legoboyvdlp** [comment]
Specifically, remove -dev from the folder name, as it says in the instructions :)
