### ISSUE TITLE
Bug - Cannot switch lower ECAM pages whilst enroute

### ISSUE THREAD

**Issue by MiSKLaCH** [legoboyvdlp/A320-family#195]
**Describe the bug**
Even though the ECAM pages buttons are working on the ground, I noticed they won't work anymore whilst the aircraft is enroute. Nasal debug console shows an error (see screenshot).

**To Reproduce**
Steps to reproduce the behaviour:
1. Program the aircraft, the buttons are working
2. Take off and reach cruise FL
3. Try switching ECAM pages via the buttons
4. If not working, as in my particular case, check out the error in nasal debug console

**Expected behaviour**
ECAM pages buttons should work as usual

**Screenshots**
![Screenshot_2020-11-21_12-25-52](https://user-images.githubusercontent.com/15834441/99884352-fde92e80-2c2d-11eb-83b3-f7b2e1d2ea90.png)

**System (please complete the following information):**
 - OS: Ubuntu Linux 18.04.5 LTS
 - FlightGear version: 2020.3.1

**Comment by legoboyvdlp** [comment]
I just had another report of this. I can't reproduce it myself, it works fine here. Did you try after the last commit I did just a few minutes ago?

**Comment by MiSKLaCH** [comment]
I'm up to date with the latest commit, buttons work fine before and after the flight but they don't enroute... strange issue indeed.
Edit: I see last commit is 7 hrs old:
![latest_commit](https://user-images.githubusercontent.com/15834441/99884488-dc3c7700-2c2e-11eb-959a-6310e84cd9f4.png)

**Comment by legoboyvdlp** [comment]
Oh, that maybe explains it because I was trying on the ground ... :v

and that is very bizarre

**Comment by legoboyvdlp** [comment]
(Ah, I didn't push that commit ... just done. Will try and reproduce in flight now. )

**Comment by legoboyvdlp** [comment]
Ah, found it! The cruise page doesn't have a light so naturally it fails :)
