### ISSUE TITLE
Bug - PFD altitude bug unaligned and bouncing around

### ISSUE THREAD

**Issue by MiSKLaCH** [legoboyvdlp/A320-family#196]
**Describe the bug**
I noticed this issue as soon as I switched from local QNH to STD.
The altitude bug of both PFDs became unaligned compared to the altitude indication.
See screenshots, in every captured image the aircraft was in level flight and the AP altitude bug was significantly off the indicated altitude. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Prepare the aircraft for flight
2. Take off
3. At transition altitude switch to STD QNH
4. As AP levels off at selected altitude check the altitude bug against the indicated altitude

**Expected behaviour**
AP altitude bug should reflect the correct value in the altitude tape

**Screenshots**
![ap_alt_w](https://user-images.githubusercontent.com/15834441/100157442-d81c8d80-2eaa-11eb-987a-10f30188501d.png)
![ap_alt](https://user-images.githubusercontent.com/15834441/100157453-dc48ab00-2eaa-11eb-9706-6e66f17c41a0.png)
![fgfs-20201124211946](https://user-images.githubusercontent.com/15834441/100157365-b6230b00-2eaa-11eb-97fd-e36136c21423.png)
![fgfs-20201124212210](https://user-images.githubusercontent.com/15834441/100157379-bcb18280-2eaa-11eb-92c4-846e8393c13f.png)
![fgfs-20201124215013](https://user-images.githubusercontent.com/15834441/100157390-bf13dc80-2eaa-11eb-902f-7122afe4b2c9.png)

**System (please complete the following information):**
 - OS: Ubuntu Linux 18.04.5 LTS
 - FlightGear version: 2020.3.1

**Comment by legoboyvdlp** [comment]
This one is weird, that part of the code  hasn't changed either, so I need to try and figure out what is going wrong ...  thanks for the report!

**Comment by legoboyvdlp** [comment]
Nevermind, it was my fault, fixed locally now.
