### ISSUE TITLE
Elac computers bug.

### ISSUE THREAD

**Issue by 111ukasz111** [legoboyvdlp/A320-family#198]
System and specifications: Windows 10, 4gb ram, intel core i7, Geforce 920m, 
1. Turn off Elac 1 and Elac 2.
2. Elac 1 and Elac 2 aren’t red on screen. 
![A320 Elac 1 and Elac2 off is not red](https://user-images.githubusercontent.com/20667528/100873730-e3bc1580-34a3-11eb-8b00-59e45c3760bb.JPG)

**Comment by merspieler** [comment]
Please always check the latest version, before opening an issue.
This already works correctly on dev branch.
