### ISSUE TITLE
Fatal exceptionBug - 

### ISSUE THREAD

**Issue by braval2237** [legoboyvdlp/A320-family#199]
It downloads properly but it wont let me load the aircraft into the simulator because of a fatal exception

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**

**Screenshots**

**System (please complete the following information):**
 - OS: 
 - FlightGear version: 

**Additional context**

**Comment by merspieler** [comment]
sorry, but we need more information.

If you've got more information like the fgfs.log, please reopen this issue

**Comment by legoboyvdlp** [comment]
almost certainly caused by lack of reading installation instructions!

**Comment by braval2237** [comment]
Okay so i went back and read the instructions but now im confused as to how to rename the aircraft,do i just rename it from the windows file or is it a different way?
Thanks for the help btw

**Comment by Marsdolphin** [comment]
Rename the folder
