### ISSUE TITLE
Feature request: GPU available with parking brake off when chocks in place

### ISSUE THREAD

**Issue by merspieler** [legoboyvdlp/A320-family#2]
### General
----

I am submitting a: (select one) 
* [ ] Bug report
* [x] Feature request

### Details
----

#### Current Behavior (if applicable)

When parking brake is set to off, gpu get's removed

#### Requested Behavior  (feature requests)

Keep gpu when chocks are set.

IRL the parking brake is released once the chocks are in place to the the brakes cool down

**Comment by legoboyvdlp** [comment]
Solved in 299e387.
