### ISSUE TITLE
Bug - Non-engine/apu sounds not playing correctly

### ISSUE THREAD

**Issue by hayden2000** [legoboyvdlp/A320-family#20]
**Describe the bug**
This has been a reoccurring problem for awhile with this aircraft, but there are issues with the non-engine sounds depending on the variant (might be a Mac issue).

**Additional context**
IAE: The engine/apu sounds work without issues. Initially all other sounds work, however after a seemingly random amount of time, all non-engine/apu sounds will stop working. I have found a workaround:
- Pause the sim
- Click out of FG window into another application
- Return to FG
- While still paused, trigger a sound (i.e. I use the seat belt sign usually)
- Unpause the sim, all the sounds now work correctly
On a typical flight (~1 hours), I have to repeat this process 3-4 times on average.

CFM: None of the non-engine sounds work, fix for IAE does not work. APU sound only works after cycling through internal and external views a couple of times. Previously had the same issues as the IAE, but all sounds were broken after the new sounds update a month or two ago.

**To Reproduce**
Steps to reproduce the behaviour:
1. Start up A320, choosing CFM or IAE variant
2. Try starting up (either manually or using configuration, doesn't make a difference)
3. Sounds don't play correctly (described above)

**Expected behaviour**
I would expect all sounds to work for the entire duration of the flight.

**System**
 - OS: macOS 10.15
 - FlightGear version: 2019.1.1

Wish I could help more with the project, but pretty busy with other programming projects at the moment. Hopefully I can help out more in the future, though.

**Comment by legoboyvdlp** [comment]
Revision.txt please?

**Comment by hayden2000** [comment]
Currently on 4

**Comment by hayden2000** [comment]
I've done some testing and the issue appears isolated to macOS, as I tried using the aircraft on Windows 10 and it worked just fine. I am going to try using a few other Macs I have access to and see if I can get the aircraft to work on them. In the meantime, let me know if I can help with this bug in any way, as I know most of you are on Windows/Linux.

**Comment by legoboyvdlp** [comment]
I quite simply cannot reproduce on Windows.

Checking on Mac would be good.

**Comment by hayden2000** [comment]
In addition to main Mac, which already doesn't work.

I tried a secondary Mac that already had FG installed and it didn't work.

Plus I tried a clean install of FG on a third Mac and it still didn't work.

**Comment by legoboyvdlp** [comment]
Someone on mac says IAE works. So that matches what you say that IAE works sometimes, sometimes not (which is even more wierd).

**Comment by bunnyhappy** [comment]
Working on figuring out what is going on, I did find this error given in the fgfs.log every time I trigger a sound that doesn't play:
/Users/Shared/Hudson/MacRelease/simgear/simgear/sound/soundmgr_openal.cxx:868:AL Error (sound manager): Unknown Internal Error at sample play

**Comment by hayden2000** [comment]
Working on figuring out what is going on, I did find this error given in the fgfs.log every time I trigger a sound that doesn't play:
[ALRT]:sound      /Users/Shared/Hudson/MacRelease/simgear/simgear/sound/soundmgr_openal.cxx:868:AL Error (sound manager): Unknown Internal Error at sample play

Also found what appears to be a somewhat related issue: https://github.com/kcat/openal-soft/issues/337

**Comment by legoboyvdlp** [comment]
That definitely sounds like a typical dependency bug (given that it is platform specific) so yeah probably best to ask openAL to see if they have a solution. Notice FlightGear can and has done fixes - we can't fix bugs actually in openAL but we can fix things in the API used to talk to openAL

**Comment by mattmaring** [comment]
I've made an initial fix for the sounds on Mac. It appears that the external sounds are the culprit for the missing sounds. I'll keep tweaking this to make sure its working correctly, but it appears the external sounds need to be explicitly disabled while in internal views. I'd imagine there is a more efficient way to do this, but this did work quite well on Mac.

**Comment by legoboyvdlp** [comment]
That looks fine, is it ready to merge back?

**Comment by mattmaring** [comment]
Yeah, I'd say so. Added a pull request

**Comment by dirteat** [comment]
@hayden, which version of openAL do you have installed. Started to get exactly the same problems with the Shuttle, loosing external sounds at some point. It started with openAL >= 1.19.
Thanks!

**Comment by mattmaring** [comment]
I have openAL 1.19.1. At least for the A320, the problem was not explicitly silencing external sounds in the internal views. Definitely an annoying bug with openAL.
