### ISSUE TITLE
Bug - Fatal Exeption, cannot launch

### ISSUE THREAD

**Issue by macmmm81** [legoboyvdlp/A320-family#205]
**Describe the bug**
After an installation of FlightGear and then the aircraft I tried to launch the game with this aircraft selected. Game cannot load.

**To Reproduce**
Steps to reproduce the behaviour:
Open simulator, select A320 and fly.

**Screenshots**
![image](https://user-images.githubusercontent.com/39221755/105212348-9ed06900-5b4d-11eb-96d2-1f52284b254f.png)

**System (please complete the following information):**
 - OS: Windows 10 (20H2)
 - FlightGear version: 2020.3.5

**Comment by legoboyvdlp** [comment]
Fatal exception: didn't read installation instructions :joy:

**Comment by legoboyvdlp** [comment]
To be clear you need to remove whatever Git adds to the end of the folder name. For example `-dev`.
