### ISSUE TITLE
Bug - ELEC EMER CONF on startup

### ISSUE THREAD

**Issue by merspieler** [legoboyvdlp/A320-family#21]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:
1. Turn BAT 1 and BAT 2 on
2. Observe Master Warning and ELEC EMER CONF on E/WD

**Expected behaviour**
Silent power up

**Screenshots**

** System (please complete the following information):**
 - OS:
 - FlightGear version:

**Additional context**

**Comment by legoboyvdlp** [comment]
That's odd. I tried that before and never got that.

Something to do with different initialization speed I imagine...

**Comment by legoboyvdlp** [comment]
Ok, reproduced, something is wrong in static inverter.

**Comment by legoboyvdlp** [comment]
Found and fixed (I think)!
