### ISSUE TITLE
Bug - VHF3 data mode got broken on next due to core changes

### ISSUE THREAD

**Issue by merspieler** [legoboyvdlp/A320-family#212]
previously setting `/instrumentation/comm[2]/frequencies/selected-mhz` to 0 switched the VHF3 into data mode.

This is no longer possible as it gets reset to a valid frequency.

We need another property for it now..... any proposals?

**Comment by legoboyvdlp** [comment]
I'm not sure. Maybe the radios need revised anyway

**Comment by merspieler** [comment]
What should get changed? Other than fixing the issue?  
... for VHF that is, HF and the other stuff never worked.
