### ISSUE TITLE
Feature Request - Sound Pack

### ISSUE THREAD

**Issue by AAL5665** [legoboyvdlp/A320-family#215]
Some switch appear to not have sound implemented in them when click. E.g: Parking Brake, Engine Switch, Engine Mode Selector and Knobs

Please note that this is not forceful if not possible at the moment.
Link to some sounds: [https://www.youtube.com/watch?v=mLA6ZTAdqb0](url)

**Comment by merspieler** [comment]
If you hope, we could copy the sounds from them, you've got to talk to them as they release it under the GPL3 which is not compatible with GPL2 which we use.

Also some of the sounds in the video don't seem to have an accurate sound to it....

**Comment by AAL5665** [comment]
How does the remote MCDU work (your-flightgear-computer) what do that mean?

**Comment by AAL5665** [comment]
Sound system.
The cockpit seems to be a lot loud when the two engines have started during a flight(after startup and until engine shutdown)
I was wondering whether this is a bug or just the wrong sound?

**Comment by AAL5665** [comment]
@merspieler Hello?

**Comment by merspieler** [comment]
I am NOT 24/7 instant support.... so please be patient... if I, or someone else need a couple of days to replay, then you've got to wait... In the end you're not paying us and we do it in our free time, so we've got exactly zero obligations!

Regarding the sound, I don't get whats your issue...

**Comment by AAL5665** [comment]
@merspieler sorry if I offended I didn't mean to get you angry just want to check if you were there. I am aware you aren't a bot so that is why I didn't continue to say anything until you replied.

I will send you an attachment regarding my issue.

**Comment by AAL5665** [comment]
Issue = Cockpit gets louder when engines are start
Reference:
https://www.youtube.com/watch?v=SUJIa3aAyAg

**Comment by merspieler** [comment]
If you turn on the enignes, it obvisouly gets louder.

And please always use a link with a timestamp... we can't watch 10 minutes videos just to find a 30 seconds sequence.

**Comment by AAL5665** [comment]
I agree but after the startup it gets a lot louder in that cockpit than it should and the exterior gets a bit quieter than the cockpit

**Comment by AAL5665** [comment]
EXT Power connect before and after sound:
https://www.youtube.com/watch?v=3kvSH6QC6y0
Sound = 0:11 - 0:37
Addition sound = 0:51 - 1:04

**Comment by merspieler** [comment]
Now I'm even more confused... the video doesn't even show engine startup.
What you can hear, once the acft has power, is the cooling fan.

Not sure which additional sound you mean.

**Comment by AAL5665** [comment]
My last comment was not on the startup but on actual sounds.

**Comment by merspieler** [comment]
You mean the APPR CAT downgrade sound...
I'm not quite sure, why it happens... can you find any documentation for it please.

**Comment by AAL5665** [comment]
From I've seen it happens after the aircraft boots up

**Comment by merspieler** [comment]
Duh... that I can see too... but why? Which system is responsible?

**Comment by AAL5665** [comment]
> You mean the APPR CAT downgrade sound...
> I'm not quite sure, why it happens... can you find any documentation for it please.

https://www.youtube.com/watch?v=fQH_ngA_smg
4:35-4:42

**Comment by merspieler** [comment]
Yeah... that's first the AP DISC sound and then the APPR CAT downgrade sound...

I've asked for documentation... on why it happens on startup...
I know why it happens in this video, that's stated in the FCOM.

**Comment by AAL5665** [comment]
just to be sure that was in regards to the ap disengage sounds without continuous warning sounds until warning button is pressed.

**Comment by merspieler** [comment]
Then write that with the link... we can't read minds...
Also, what you can not tell for the video is if the PF cancels the warning manually....

**Comment by AAL5665** [comment]
Back on the topic: BATT/EXT PWR sounds and button pressed sound

https://www.youtube.com/watch?v=ZiyR4juG1hE

Cockpit After Engine Start: 1:20-1:50
"Cockpit sounds remain the same after startup
https://www.youtube.com/watch?v=ytnLBAkRFQE

**Comment by merspieler** [comment]
What do you want to say with that??? We know how to use youtube.

**Comment by AAL5665** [comment]
👍

**Comment by merspieler** [comment]
Closing this issue cause it's stale and doesn't really add anything specific
