### ISSUE TITLE
Bug - aircraft slides in high winds

### ISSUE THREAD

**Issue by legoboyvdlp** [legoboyvdlp/A320-family#22]
Aircraft will slide in winds >20 knots uncontrollably (seen on A320). Revise friction.

**Comment by Marsdolphin** [comment]
Bug happened again. 
https://forum.flightgear.org/viewtopic.php?f=4&t=36410&start=450

**Comment by legoboyvdlp** [comment]
Fairly sure this is unrelated as I figured out that JSBSIM crashes cause it while your JSBSIM obviously didn't crash?

**Comment by Marsdolphin** [comment]
Oh ok.
The what happened to me?

**Comment by legoboyvdlp** [comment]
I don't really know to be honest.

**Comment by Octal450** [comment]
How to reproduce this? I am unable.

Kind Regards,
Josh

**Comment by Octal450** [comment]
Still unable to reproduce with my updated ground model.

Kind Regards,
Josh

**Comment by legoboyvdlp** [comment]
I can't reproduce it either, but it was somewhat of a weird issue. I'll close and if it ever happens again I'll reopen.
