### ISSUE TITLE
Remote MCDU

### ISSUE THREAD

**Issue by AAL5665** [legoboyvdlp/A320-family#220]
I am having difficulty in setting it up. Anyone know how I can use it?

**Comment by merspieler** [comment]
Just read the [README](https://github.com/legoboyvdlp/A320-family#remote-mcdu)

**Comment by AAL5665** [comment]
Just so you know I can not understand after reading over.

**Comment by merspieler** [comment]
you take the [mcdu.html](https://raw.githubusercontent.com/legoboyvdlp/A320-family/dev/mcdu.html) and save it in your FGData directory under the Phi directory (where FGData is, depends on your system and method of install)

Then you need to add the `--httpd=8080` option to flightgear, either on the command line or in the launcher.

Then start flightgear.
For a first test, open [this link](http://localhost:8080/mcdu.html) on the _same_ computer as you run flightgear.

Later on you can connect from another Computer or other device.
For that you go to `http://<IP>:8080/mcdu.html` where you have to replace the `<IP>` with the IP address of the computer where flightgear runs on. Make also sure, you allow connections to port 8080 in your computers firewall.

PS: Stating what you don't understand makes thing much easier for helping you as right now, I have to guess, what you've got already and what didn't work.
