### ISSUE TITLE
Bug - MCDU.html Buttons not aligned

### ISSUE THREAD

**Issue by Honu4** [legoboyvdlp/A320-family#221]
I know this is not a part of the A320 per se, but this is a brilliant addon. I love it. Unfortunately on my iOS 14.4 iPhone 8 Plus, the buttons do not align with the text.

**To Reproduce**
Steps to reproduce the behaviour:
1. Access MCDU.html on iPhone

**Expected behaviour**
the buttons should line up closer to text

**Screenshots**
see pic

**System (please complete the following information):**
 - OS: MacOS v 10.15.7
 - FlightGear version: V2020.3.6

**Additional context**
absolutely brilliant idea and execution
Cheers!
![15157BD2-613C-4318-A701-8536ED0A5F93](https://user-images.githubusercontent.com/67807217/111043338-1ef4ab80-83e6-11eb-8817-2a2e29d53e5a.png)
![IMG_88766E1BFD82-1](https://user-images.githubusercontent.com/67807217/111043392-624f1a00-83e6-11eb-8586-3b2f162c4481.jpeg)
<img width="333" alt="Screen Shot 2021-03-13 at 10 26 31 AM" src="https://user-images.githubusercontent.com/67807217/111043435-962a3f80-83e6-11eb-9d74-94797fe8d1a5.png">
![IMG_0A6589DA1C4E-1](https://user-images.githubusercontent.com/67807217/111043445-a7734c00-83e6-11eb-852c-52ade037bfce.jpeg)

**Comment by NewoIsTaken** [comment]
Hey @Honu4, I am currently working on a new and improved `mcdu.html`. An error on my part is that I did not test it on mobile. In FlightGear, the MCDU that pops up is always the same size (I believe) which make it easier to layout. Unfortunately lining everything up and having it be resizable is hard. For now, you will have to use it as is.

**Comment by Honu4** [comment]
@NewoIsTaken, Thanks for the quick follow up. Much appreciated. And thanks for this add-on. I understand itʻs in its infancy and it is quite useable as is. I look forward to updates.
Cheers!

**Comment by NewoIsTaken** [comment]
@Honu4, I actually did not create this addon, please direct your thanks to @niner! :smile:

**Comment by Honu4** [comment]
@niner!!!!! Apologies. Please excuse my ignorance. 
Cheers!

**Comment by inuyaksa** [comment]
Hello @niner and @NewoIsTaken , great work for http mcdu, very useful using on my tablet! ;)
I suggest you some mods for a more comfortable usage on mobile.
Add these css props to buttons (td) 			
touch-action: manipulation;
user-select: none;		
to prevent text selections and zoom on double tap.
Add oncontextmenu="return false;" to body to prevent context menu popping out on a long tap.
I hope working well on ios and android too.

If possible add a request for a wishlist, I would love a version for tablet on landscape mode with mcdu on the left and keyboard on the right side. :)

**Comment by NewoIsTaken** [comment]
@inuyaksa Thanks for the suggestions! I will certainly consider them when creating the new one.

**Comment by AAL5665** [comment]
@Honu4 how did you get it to work?

**Comment by AAL5665** [comment]
mcdu.html does not open and leaves the message ('404 not found')

**Comment by AAL5665** [comment]
![Screenshot 2021-03-16 at 4 46 08 PM](https://user-images.githubusercontent.com/74672200/111347659-5463f800-8677-11eb-8003-ff68482703c6.png)

**Comment by niner** [comment]
@AAL5665 did you follow the instructions in the A320's README?

**Comment by AAL5665** [comment]
https://user-images.githubusercontent.com/74672200/111361357-a744ac00-8685-11eb-83cb-3f413524fe41.mp4

**Comment by AAL5665** [comment]
@niner Found the problem sorry for the trouble

**Comment by niner** [comment]
Can you tell us what it was? Could be useful if someone else has the same 
problem.

**Comment by AAL5665** [comment]
@niner (Using Mac) I duplicated the package content in order to access the aircraft folder for swift. After reading the README I placed the mcdu.html in the duplicated folder of FlightGear(its package content for swift) making it ineffectively when I started FlightGear itself(because I first used windows until recently).

your-flightgear-computer is your computer's ip address


https://user-images.githubusercontent.com/74672200/111469540-b88dc700-871e-11eb-9ffe-884493bf8328.mp4

**Comment by NewoIsTaken** [comment]
@AAL5665, could you attach your `$FG_HOME/FlightGear/FlightGear.ini` file here? Should be at: `~/Library/Application Support/FlightGear/FlightGear/FlightGear.ini`.

**Comment by Honu4** [comment]
> @niner (Using Mac) I duplicated the package content in order to access the aircraft folder for swift. After reading the README I placed the mcdu.html in the duplicated folder of FlightGear(its package content for swift) making it ineffectively when I started FlightGear itself(because I first used windows until recently).
> 
> your-flightgear-computer is your computer's ip address
> 
>  2021-03-17.12-44-10.mp4

Thanks for pointing out this workaround for accessing the program package for this and other non-Mac-friendly applications requiring access to a data folder buried in the package. I was able to edit the path in Swift so I didn't realize that this is a good tip.

Mahalo

**Comment by NewoIsTaken** [comment]
@Honu4 you can try to duplicate the `FGData` folder and then set `fg-root-2020-3-6=/home/newo/Applications/FlightGear/2020.3.6/fgdata` in `$FG_Home/FlightGear/FlightGear.ini`. You should be able to find your `FGData` folder by right clicking on `/Applications/FlightGear`. And selecting `Show Package Contents`. In there, you should be able to poke around and find a folder that says `Data`, `FGData` or some variant of that in the `Resources` folder or something. You might need to do some digging.

**Comment by NewoIsTaken** [comment]
@inuyaksa why did you close this?
