### ISSUE TITLE
Feature Request -  MCDU AIRWAYS

### ISSUE THREAD

**Issue by AAL5665** [legoboyvdlp/A320-family#223]
I would like to suggest that you use flightGear's airway data for now if possible.

**Comment by merspieler** [comment]
As soon, as airways are working, we will obviously use what ever is available in flightgear... what else would we use?

**Comment by AAL5665** [comment]
I was referring to the AIRWAYS being usable in flightGear now. Guess I mistook it for being in line with fmsdata

**Comment by AAL5665** [comment]
@merspieler Sorry about that 😢

**Comment by merspieler** [comment]
The awy.dat.gz is in FGData since 2013-12-13...  
And yes, it probably can be used with an FMS that's designed to make use of it... we're not there yet.

AND STOP TAGGING ME.
