### ISSUE TITLE
Bug - Can't scroll through the available TRANSITIONS

### ISSUE THREAD

**Issue by 777joe** [legoboyvdlp/A320-family#226]
When Transitions are appear in the ARRIVALS page, we cant scroll through all the available transitions, and only the first 3 transitions are available

I have navigraph data for the procedures. All the side and stars work fine.

**System (please complete the following information):**
 - OS: Windows 7 32 bit
 - FlightGear version: 2020.3.8

**Comment by merspieler** [comment]
Can you please let us know with which airport and STAR we can test this.

Most airports don't have that many transitions.

**Comment by 777joe** [comment]
TNCM airport, ULUBA star, RNV10 approach. The TRNKY transition cannot be seen. Trying to manually type into TRANS doesn't work. This is in the 2103 AIRAC cycle.

**Comment by legoboyvdlp** [comment]
Fixed?
