### ISSUE TITLE
Bug - Plae start engine while all fuel pumps are OFF

### ISSUE THREAD

**Issue by velteyn** [legoboyvdlp/A320-family#229]
**Describe the bug**
Hello, I don't know if at this stage of development this can be considered a bug or a missing feature but the fact is that I was able to start the plane engine with all fuel pumps to OFF position.

**To Reproduce**
1. Start battery pack 1 and 2
2. press APU master switch
3. start APU
4. wait for APU to startup and wait for AVAIL START
5. switch engines knob to Start
6. Raise the engine no1 lever
7. The engine starts..

**Expected behaviour**
I think that a logic behavior with all the fuel pumps to OFF should not start at all.. 

**Screenshots**
![fgfs-20210523090212](https://user-images.githubusercontent.com/1019294/119254648-c09f3280-bbb7-11eb-993b-35e9af131757.png)
![fgfs-20210523090221](https://user-images.githubusercontent.com/1019294/119254656-c72daa00-bbb7-11eb-93a3-e8998682f103.png)

**System (please complete the following information):**
 - OS: windows 10
 - FlightGear version: 2020.03

**Additional context**
A320 Fuel system video
https://youtu.be/NY81Mrgtn6c

**Comment by merspieler** [comment]
This is not a bug.

The engines are fed by gravity even tho the pumps are off.
