### ISSUE TITLE
Todo - Rewrite EFIS Panel code

### ISSUE THREAD

**Issue by legoboyvdlp** [legoboyvdlp/A320-family#23]
**Is your feature request related to a problem or missing feature? Please describe.**
EFIS code is hard to read and uses old style code including getprop().

**Describe the solution you'd like**
Rewrite EFIS code using better methods. 

Requirements:
 - Uses PTS as appropriate to communicate with other systems
 - Uses props.nas code 
 - Interface with electrical system - should only work when dc-ess has power
 - FCOM functions cross-checked (i.e. confirm all features present). Of particular note - QFE mode on the altimeter
 - FCU failure: loss of both FCU channels makes EFIS inoperative, and reverts to Q1013. See https://hursts.org.uk/airbus-nonnormal/html/ch11.html#fcu-fault.

Ignore the flight director and ILS buttons; they are part of the FCU.

**Comment by merspieler** [comment]
PTS?

**Comment by legoboyvdlp** [comment]
Basically, to talk with electrical system you do it like this:

`systems.ELEC.Bus.dc1.getValue()`

and so on

Let me know if you need anything, hope this is ok ;)

**Comment by merspieler** [comment]
Sure okay, just not sure when I'll get to it.

**Comment by legoboyvdlp** [comment]
not a problem.

**Comment by legoboyvdlp** [comment]
Ammended with info about FCU fault. 

Refer to `fcu.FCUController.FCUworking` for dual channel fault.

**Comment by legoboyvdlp** [comment]
If you don't have time to do this I can try it.

**Comment by merspieler** [comment]
Go ahead... I won't getting to it before December

**Comment by legoboyvdlp** [comment]
Actually, wrong, I didn't do it yet.

**Comment by Octal450** [comment]
I'll do this for you @legoboyvdlp shortly

Kind Regards,
Josh

**Comment by legoboyvdlp** [comment]
Closed in 62931a38a5b9733f8830ccc05b74cfe38614d133
