### ISSUE TITLE
Bug - You can select the text in the remote MCDU buttons

### ISSUE THREAD

**Issue by valtsu41** [legoboyvdlp/A320-family#230]
**The bug**
When in the remote MCDU you can select the text inside the buttons. Ancient chrome version, for example selects the text every time I try to press a button.

**To Reproduce**
Just go to remote MCDU and do whatever you use to select/highlight text on your device.

**Expected behaviour**
Not being able to select the text since it is a button.

**Screenshots**
https://cdn.discordapp.com/attachments/787863358278991902/846488256773881866/Screenshot_20210524-233919_Chrome.jpg

**System:**
 - OS: Windows 10 / Android 8.0.0
 - FlightGear version: 2020.3.8

**Comment by merspieler** [comment]
> Ancient chrome version

On somewhat up-to-date chrome it doesn't select on a simple click, only when click and dragging...
Same applies to qutebrowser and Firefox, both somewhat current.

So I'd say, update your browser.

**Comment by inuyaksa** [comment]
Fixed on recent commits (remote mcdu as webpanel).
