### ISSUE TITLE
Not staying on present heading when flying open transitions (after MANUAL)

### ISSUE THREAD

**Issue by ltoenning** [legoboyvdlp/A320-family#232]
**Describe the bug**
Many airports (especially Germany) switching to open transition recently where, on downwind, there isn't a published turn to crosswind/final. Aircraft should continue on downwind and expect vectors to final from ATC.  (see https://nav.vatsim-germany.org/files/edgg/charts/eddl/public/EDDL_TRANSITION23.pdf or transition charts for EDDM/EDDF e.g. AD 2 EDDF 3-1-7 https://aip.dfs.de/basicIFR)
This is marked with a `MANUAL` waypoint in the MCDU.

Currently this does not seem to be working with the A320. It's following the transition with a direct turn to the next waypoint

**To Reproduce**
Steps to reproduce the behaviour:
1. Select an open transition (like HALME23 in EDDL)

**Expected behaviour**
Switch to heading mode on current heading after passing `MANUAL`. Draw a straight infinite line after `MANUAL`

**Screenshots**
![A320-manual-transition](https://user-images.githubusercontent.com/1716810/120936311-782f5b00-c707-11eb-965c-f6f206aab865.png)

**System (please complete the following information):**
 - OS: Linux x64
 - FlightGear version:  next (FG), dev (A320-family)

**Comment by legoboyvdlp** [comment]
Thanks - the MANUAL style leg is not yet implemented. I've got that to do on my list, but I've been waiting for quite a long time for James Turner to make some fixes so I can proceed to do that.

**Comment by legoboyvdlp** [comment]
Fixed. Now reverts to HDG. 
<img width="644" alt="image" src="https://user-images.githubusercontent.com/10434911/176438062-d18b14c6-1352-4de9-b596-d698aa5eb41a.png">

Doesn't yet render on ND but that's a limitation of the ND I can't control yet.
