### ISSUE TITLE
Bug - possible issue with spoiler

### ISSUE THREAD

**Issue by legoboyvdlp** [legoboyvdlp/A320-family#238]
Possible issue with spoiler 1 on the left / right hand side  -- check the power supply from ELACs / SECs and hydraulics. I managed to get it so spoiler 1 on the left was failed but on the right was not failed ...?

**Comment by Octal450** [comment]
Does it happen on 3D Branch? I fixed a few issues with the spoiler system on there

Kind Regards,
Josh

**Comment by Octal450** [comment]
This is fixed.
Josh
