### ISSUE TITLE
Bug - Temperature glitches out when entering float value as cruise altitude in the FMGC

### ISSUE THREAD

**Issue by leEduardo** [legoboyvdlp/A320-family#240]
**Describe the bug**
When a float value (like 3.8) is entered in the Cruise Altitude box (FMGC INIT page), the value is accepted and the temperature shown beside it shows a number with tens of decimal places. It stays like that even if you try to change the cruise altitude to a proper value.

**To Reproduce**
1. Go to 'FMGC INIT page';
2. Type a decimal number like 1.5 into the clipboard;
3. Insert it into the Cruise Altitude amber box.

**Expected behaviour**
Unable to insert/invalid value.

**System (please complete the following information):**
 - OS: Lubuntu 20.04
 - FlightGear version: 2020.3.9

**Comment by merspieler** [comment]
Why would you want to insert a float?

If I'm not mistaken, there are two issue:
* It does accept floats (shouldn't be accepted)
* Temp field always shows 14.3999999... no longer gets a new value.

**Comment by mattmaring** [comment]
Fixed in dev :)
