### ISSUE TITLE
Bug - Autoland light always turns on with ILS tuned and LS on

### ISSUE THREAD

**Issue by merspieler** [legoboyvdlp/A320-family#241]
**Describe the bug**
Autoland light is always on below 200ft when LS is on.

**To Reproduce**
Steps to reproduce the behaviour:
1. Tune an ILS
2. On the EFIS enable LS
3. Autoland light turns on

**Expected behaviour**
Autoland light turns only in following cases on:
DSC-22_30-30 P 3/4:
> The autoland red warning flashes in LAND mode when the radio altitude goes 
 below 200 ft and:
‐ The aircraft gets too far off the beam (LOC or GLIDE), or
‐ Both glide slope transmitters or receivers fail above 100 ft, or
‐ Both localizer transmitters or receivers fail above 15 ft, or
‐ The difference between both radio altimeter indications is greater than 15 ft, or
‐ Both autopilots fail.

DSC-22_30-80-30-10 P 8/10:
> The following situations, when occurring below 200 ft RA with the aircraft in LAND mode, trigger the
flashing Autoland red warning and a triple click aural warning:
‐ Both APs OFF below 200 ft RA.
‐ Excessive deviation in LOC (1/4 dot above 15 ft RA) or GLIDE (1 dot above 100 ft RA). In addition,
LOC and GLIDE scales flash on the PFD.
‐ Loss of LOC signal above 15 ft, or loss of GLIDE signal above 100 ft. The FD bars flash on the
PFD. The LAND mode remains engaged.
‐ The difference between both radio altimeter indications is greater than 15 ft.

**Comment by inuyaksa** [comment]
Working on it
