### ISSUE TITLE
Bug - FLAPS 3 GPWS Inhibit doesn't work

### ISSUE THREAD

**Issue by leEduardo** [legoboyvdlp/A320-family#245]
**Describe the bug**
When FLAPS 3 LANDING is selected in the GPWS panel it shows as ON but does not work as expected. You still get a "TOO LOW FLAPS" sound warning when trying to land configured with flaps 3.

**To Reproduce**
While in the air, configure the aircraft for landing. Push the "FLAPS 3 LDG" pushbutton into the "ON" position in the overhead GPWS panel. Gear down, select Flaps 3, select the approach speed for the autothrust, arm the speedbrakes (Note: when I noticed the bug I was doing patterns + touch-and-goes, so I didn't select autobrake). Approach the runway for landing. The "TOO LOW FLAPS" warning sounds nonetheless.

**Expected behaviour**
The GPWS warning for flaps should be inhibited when Flaps 3 is selected.

**System (please complete the following information):**
 - OS: Lubuntu 20.04
 - FlightGear version: 2020.3.9
 - A320 Version: 3D branch

**Comment by Octal450** [comment]
Fixed in e56672d0

Josh
