### ISSUE TITLE
Bug - Unable to change liveries

### ISSUE THREAD

**Issue by leEduardo** [legoboyvdlp/A320-family#246]
**Describe the bug**
It is not possible to change liveries at all with the 3D branch aircraft. It initializes with an "unpainted" livery; if you try to change it, the simulator freezes and crashes to desktop. The feature works flawlessly in the dev branch.

**To Reproduce**
Spawn in with the 3D branch aircraft. Try to change liveries through the menu. Crash to desktop.

**Expected behaviour**
Not crashing and changing the livery.

**System (please complete the following information):**
 - OS: Lubuntu 20.04
 - FlightGear version: 2020.3.9
 - A320 Version: 3D branch

**Additional context**
It doesn't happen with the dev branch. Something got messed up somewhere in the 3D branch and I suppose it will eventually make it into dev.

**Comment by SP-NTX** [comment]
I also have this bug, Windows 10, FG Nightly

**Comment by legoboyvdlp** [comment]
How much memory do you have? This does not happen here. In addition does it occur if you rescale the textures to 2048 from 4096?

**Comment by merspieler** [comment]
Could you please let us know how much VRAM you have and what's the maximum supported texture size (max texture size see Menu->Help->About near the bottom)?

**Comment by SP-NTX** [comment]
everything worked for me until today's updates

**Comment by merspieler** [comment]
please, still give the reqested values

**Comment by leEduardo** [comment]
> Could you please let us know how much VRAM you have and what's the maximum supported texture size (max texture size see Menu->Help->About near the bottom)?

I have 2GB VRAM, Max Texture Size shows 16384. Again, it works normally in dev.

**Comment by legoboyvdlp** [comment]
@SP-NTX if so can you tell me, exactly, which commit caused it to fail? Thank you.

**Comment by leEduardo** [comment]
> How much memory do you have? This does not happen here. In addition does it occur if you rescale the textures to 2048 from 4096?

I have 2GB VRAM and 8GB RAM. Could you explain further that rescaling thing?
This issue does not happen with the dev branch aircraft.

**Comment by legoboyvdlp** [comment]
I know it doesn't happen with dev as you've mentioned that before. I wouldn't expect it to, because the 3D branch is much more detailed, accurate, but also heavier in performance.


What I mean is that you open the livery texture and reduce the size in pixels to 2096*2096, and then resave the texture.

**Comment by leEduardo** [comment]
> I know it doesn't happen with dev as you've mentioned that before. I wouldn't expect it to, because the 3D branch is much more detailed, accurate, but also heavier in performance.
> 
> What I mean is that you open the livery texture and reduce the size in pixels to 2096*2096, and then resave the texture.

Where can I find these textures? The issue happens when I try to use the ones that come with the plane (Swiss or Austrian).

**Comment by legoboyvdlp** [comment]
You can find them in A320-family\Models\Liveries\A320\CFM!

**Comment by leEduardo** [comment]
> You can find them in A320-family\Models\Liveries\A320\CFM!

Rescaling to 2048 worked for the Swiss livery. I'm able to select it in the sim now. Just strikes me as odd that, being able to sustain 90 fps with the aircraft parked, simply selecting a 4096x4096 livery would make it crash... Is it only a matter of not enough RAM?

**Comment by merspieler** [comment]
> reduce the size in pixels to 2096*2096

that's actually 2048*2048

**Comment by merspieler** [comment]
>  Is it only a matter of not enough RAM?

possible... could you monitor your ram usage please.

**Comment by legoboyvdlp** [comment]
It really depends tbh, e.g. what other programs you have open? Also I can't think on any reason at all for it to change recently (today)? How much RAM do you have free before you change the livery?

**Comment by leEduardo** [comment]
> It really depends tbh, e.g. what other programs you have open? Also I can't think on any reason at all for it to change recently (today)? How much RAM do you have free before you change the livery?

So I tested RAM usage now. The aircraft spawned with the Swiss livery already selected. The RAM usage was stable at 5.5 out of 7.7GB. I then selected the Austrian livery (4096x4096). RAM spiked at 6.6 out of 7.7GB, then the sim crashed to desktop.

**Comment by merspieler** [comment]
So we've got something for you to try
Download [this zip file](https://github.com/legoboyvdlp/A320-family/files/6909837/swr.zip)
You'll find in there:

* SWR.xml, replace the original
* SWR-fuselage.dds Compressed dds texture put it besides the other textures in `A320-family\Models\Liveries\A320\CFM`
* SWR-fuselage-unc.dds Same file as above but uncompressed.

Start with a different livery than the SWR one. Then switch to SWR with the above files.

As a second step repeat the same but this time, rename the SWR-fuselage-unc.dds to SWR-fuselage.dds to test the uncompressed case (faster loading but larger size)

**Comment by SP-NTX** [comment]
> @SP-NTX if so can you tell me, exactly, which commit caused it to fail? Thank you.

I dont know.  I downloaded it at 12:30 UTC

**Comment by merspieler** [comment]
We've got one more thing to try...
Please test with the the 3D-canvas branch and see if the issue applies there as well.

**Comment by leEduardo** [comment]
> So we've got something for you to try
> Download [this zip file](https://github.com/legoboyvdlp/A320-family/files/6909837/swr.zip)
> You'll find in there:
> 
>     * SWR.xml, replace the original
> 
>     * SWR-fuselage.dds Compressed dds texture put it besides the other textures in `A320-family\Models\Liveries\A320\CFM`
> 
>     * SWR-fuselage-unc.dds Same file as above but uncompressed.
> 
> 
> Start with a different livery than the SWR one. Then switch to SWR with the above files.
> 
> As a second step repeat the same but this time, rename the SWR-fuselage-unc.dds to SWR-fuselage.dds to test the uncompressed case (faster loading but larger size)

Done. It loaded normally with the compressed texture, with a RAM usage of 4.7 out of 7.7GB (the texture I manually rescaled to 2048 used 5.5).

With the uncompressed texture, the sim froze. Didn't crash to desktop, just stood there. Had to hard reset the PC and couldn't get a RAM figure.

**Comment by merspieler** [comment]
okay, thanks... could you please try the 3D-canvas branch

**Comment by leEduardo** [comment]
> okay, thanks... could you please try the 3D-canvas branch

Will do... booting up the PC now

**Comment by leEduardo** [comment]
> okay, thanks... could you please try the 3D-canvas branch

Changing liveries worked perfectly fine in 3d-canvas, both the Swiss and Austrian liveries.

**Comment by merspieler** [comment]
great, thanks for testing

@SP-NTX could you please test the 3d-canvas branch as well.

**Comment by leEduardo** [comment]
> great, thanks for testing
> 
> @SP-NTX could you please test the 3d-canvas branch as well.

One more question, what can I do to install other liveries (from the livery repo) and make them work?

**Comment by merspieler** [comment]
on 3D branch, copy the livery .xml and .png files into the livery dir of the right variant.
3D-canvas branch is still very WIP so I won't give instructions on how to do that... (isn't that hard to figure out tho ;-)
