### ISSUE TITLE
Bug - PROG FMGC page glitches out on cruise

### ISSUE THREAD

**Issue by leEduardo** [legoboyvdlp/A320-family#248]
**Describe the bug**
Once you reach and maintain the programmed cruise altitude, the PROG page keeps flickering rapidly between CRZ and DES, making it unusable. It only comes back to normal when you actually begin to descend.

**To Reproduce**
Steps to reproduce the behaviour:
1. Setup a flight as usual in the FMGC (navigation and performance).
2. Select the cruising altitude in the MCP, takeoff, OP CLB until you reach the selected altitude.
3. Go into the PROG page in the MCDU. In stable, cruise flight, it flickers constantly between Cruise and Descent.

**Expected behaviour**
Stay in CRZ phase while actually cruising.

**System (please complete the following information):**
 - OS: Lubuntu 20.04
 - FlightGear version: 2020.3.9 
 - A320 Version: 3D and 3D-canvas

**Comment by legoboyvdlp** [comment]
Confirmed. Although its PERF, not PROG.

**Comment by legoboyvdlp** [comment]
Actually, both PERF and PROG.

**Comment by legoboyvdlp** [comment]
Fixed
