### ISSUE TITLE
Todo - make clock / chrono work

### ISSUE THREAD

**Issue by legoboyvdlp** [legoboyvdlp/A320-family#25]
**Is your feature request related to a problem or missing feature? Please describe.**
Neither the ND chronometer or the cockpit clock work.

**Describe the solution you'd like**
Make them work.

**Additional context**
Might need 3D work from @TH-555, as I recall the clock isn't ready for animating.

**Comment by vezza** [comment]
Is it possible to overlay a canvas text over the chrono?

**Comment by legoboyvdlp** [comment]
I'm not sure, might be possible?

Or OSG text as well. Maybe more efficient.

**Comment by vezza** [comment]
Don't know if it is possible... it seems that canvas is to be preferred over OSG text, see: https://forum.flightgear.org/viewtopic.php?t=36287

Anyway I'm going to try OSG text as it seem way more simple to implement...

**Comment by vezza** [comment]
Hi, I've pushed some new code into chrono_dme branch... the following should work, please test for bugs:
- DME1 and DME2 indicator's on DDRMI (flightdeck)
- chrono (flightdeck)
- clock (flightdeck)
- ET chrono (flightdeck)
- Rudder trim indicator (pedestal)

Unfortunalely my 3D skills are very basic and probably I did something wrong as now the Clock_glare.png doesn't gets shown on the clock... If you know why please tell me or fix it.

**Comment by vezza** [comment]
I'm still working on the chrono logic... it should count till 99:59 (min:sec) actually it counts to 59:59 (min:sec)

**Comment by vezza** [comment]
Ok now the chrono is fixed... it is fine for me (except for the Clock_glare.png)

**Comment by vezza** [comment]
Do someone tested the chrono? After rebuilding FG next from source it doesn't work anymore
