### ISSUE TITLE
Bug - Manual engine start does not work

### ISSUE THREAD

**Issue by leEduardo** [legoboyvdlp/A320-family#256]
**Describe the bug**
The manual engine start procedure does not work. Engine start and even PTU sounds play, but the engine parameters do not move.

**To Reproduce**
Steps to reproduce the behaviour:
1. Start the APU.
2. Turn APU bleed on.
3. Turn the engine mode knob to IGN/START, check engine parameters green in upper ECAM.
4. Press the ENG MAN START pushbutton in the overhead panel.
5. The engine parameters do not budge, although the engine start and even PTU sounds play in the background.
6. Also doesn't work when one engine is already started (cross-start).

**Expected behaviour**
The start valve for the engine should open after pushing ENG MAN START and N2 should rise with >30 PSI in the system, allowing manual engine start.

**System (please complete the following information):**
 - OS: Lubuntu 20.04
 - FlightGear version: 2020.4 
 - A320 Version: 3D latest

**Comment by legoboyvdlp** [comment]
You keep making random weird forks with messed up branches. I'd advise you not do that. The branches are not compatible when merged.

**Comment by leEduardo** [comment]
> You keep making random weird forks with messed up branches. I'd advise you not do that. The branches are not compatible when merged.

Well this issue isn't related to that. I just downloaded a copy straight from the official repository and got the bug. I usually fork branches so I can test new features as they are released but this isn't related.

**Comment by Octal450** [comment]
@leEduardo Don't fork to test. Instead, git pull from our repo. Then *if you want* you can push to your fork. There is *NO* need to fork ever, unless you are planning to commit changes and make a pull request to our repo. 

If you want to test branches, use git to clone and checkout the branch, or download the zip from the branch selected instead of dev.

Anyways this is a known issue, will be resolved when I rewrite ignition system.

Kind Regards,
Josh

**Comment by legoboyvdlp** [comment]
If you test branches -- and merge them randomly -- you **will** run into difficulties, as I said the branches are **not** compatiable.

**Comment by leEduardo** [comment]
@legoboyvdlp OK sir, got it, again the problem isn't related to that.

**Comment by Octal450** [comment]
Fix in progress.

Josh

**Comment by Octal450** [comment]
![image](https://user-images.githubusercontent.com/25598604/157085994-1961617e-ddf7-49fa-bec0-a0eb221633f9.png)

Fixed. Will be on the 3D branch soon as the ignition overhaul is pushed.

Kind Regards,
Josh
