### ISSUE TITLE
Bug - Screens are black and display DISABLED

### ISSUE THREAD

**Issue by justkowal** [legoboyvdlp/A320-family#258]
**Describe the bug**
Screens are black and display DISABLED
It's fresh install, both of flightgear and airplane

**To Reproduce**
Steps to reproduce the behaviour:
1. Start game
2. See Black screens with DISABLED text

**Expected behaviour**
Normal screens showing what they should

**Screenshots**
![fgfs-20211118070328](https://user-images.githubusercontent.com/49843860/142368179-9e118a2b-e5d9-49ed-8047-be6f00ea8e1f.png)
![fgfs-20211118070355](https://user-images.githubusercontent.com/49843860/142368184-48aaf297-f716-44bb-94a6-5119890de871.png)

**System (please complete the following information):**
 - OS: Manjaro 21.1.6 Pahvo (x86_64 Linux 5.13.19-2-MANJARO)
 - FlightGear version: 2020.3.11
 - A320 Version: Latest 3D branch

**Additional context**
I have ALS disabled and I fixed my shaders when prompted

**Comment by merspieler** [comment]
which airport is that?

**Comment by justkowal** [comment]
Uhh it's EPCH is it important tho?

**Comment by merspieler** [comment]
Airports with terrain problems can cause a disabled aircraft state, EPCH is fine tho.

Could you please post the log so we can see if there are any errors in it

**Comment by Octal450** [comment]
CANVAS is not initializing.
Show me log file or nasal console please.

Kind Regards,
Josh

**Comment by legoboyvdlp** [comment]
@justkowal

**Comment by justkowal** [comment]
Sure, will provide it soon

**Comment by Octal450** [comment]
@justkowal Any update?

Kind Regards,
Josh
