### ISSUE TITLE
Todo - electrical system

### ISSUE THREAD

**Issue by legoboyvdlp** [legoboyvdlp/A320-family#26]
**Is your feature request related to a problem or missing feature? Please describe.**
Electrical system - check stability and complete

**Describe the solution you'd like**
Should have:
- complete ECAM warnings
- power / load simulation done
- fixed EMER ELEC CONFIG message
- work through FCOM distribution table and AMM tests
- circuit breakers - prepare for inclusion in 3D
- did I forget the galley buses?

**Comment by merspieler** [comment]
What's the status here?

**Comment by legoboyvdlp** [comment]
EMER elec fixed, galley buses afaik too, ECAM warnings

power / load / CB not done

**Comment by legoboyvdlp** [comment]
Batteries done

**Comment by legoboyvdlp** [comment]
Closed because informal TODO moved to Discord, most of this bar power / load simulation done is complete

**Comment by merspieler** [comment]
?

**Comment by legoboyvdlp** [comment]
?

**Comment by merspieler** [comment]
what do you mean, move to discord?

**Comment by legoboyvdlp** [comment]
![image](https://user-images.githubusercontent.com/10434911/147879253-c86005b7-26ee-47fc-b69f-da4e2b096eb4.png)

**Comment by merspieler** [comment]
but why???

It's no longer public... nor available on our mattermost...

**Comment by legoboyvdlp** [comment]
It is both public and convenient. 

Also, it's my personal list, used for my reference - so I'll put it wherever it's most convenient!

**Comment by merspieler** [comment]
how can I view it without a discord account??? cause a) I don't agree to their TOS and piracy policy and b) even if I did, they wouldn't let me sign up... I've tried...

**Comment by legoboyvdlp** [comment]
I don't believe that's possible.
