### ISSUE TITLE
Feature Request - Improved liveries

### ISSUE THREAD

**Issue by naviat-dev** [legoboyvdlp/A320-family#263]
With the standard paintkit for the A320, it has the texture for the wings, landing gear, and engine spiral. However, those files are already in other places, and the textures in the livery file have become redundant. Rather than having those textures there, you could replace it with something that looks cooler on the plane (e.g. gear doors, undercarriage, etc.)

**Comment by merspieler** [comment]
There will be a new paintkit once the 3D model is ready

**Comment by legoboyvdlp** [comment]
Correction - there *is* a new paintkit :)
