### ISSUE TITLE
Feature Request - Livery Contribution

### ISSUE THREAD

**Issue by naviat-dev** [legoboyvdlp/A320-family#264]
I have developed a texture for the a320 in 4K resolution, and I want to be able to contribute my liveries to this project. How can I do that? Thanks.

**Comment by merspieler** [comment]
is that for the old model or the one on 3D branch?

If it's for the old one, we no longer will include any of it, if it's for the new one, see https://github.com/legoboyvdlp/A320-family-liveries

**Comment by legoboyvdlp** [comment]
Please post the texture, can't do anything without seeing the texture.

**Comment by naviat-dev** [comment]
I made textures for the A320, and for the A319 and A321 when they will be added eventually. Note that these are only CFM variants; i have multiple variants for different engines and winglets.
![A319-CFM](https://user-images.githubusercontent.com/73054858/152633096-f62be9b4-57f3-47fd-b6ef-57e54b08c50e.png)
![A320-CFM](https://user-images.githubusercontent.com/73054858/152633102-cf4cdecb-6475-49fc-9341-2d0ad064bc29.png)
![A321-CFM](https://user-images.githubusercontent.com/73054858/152633105-08b4a633-98e9-45e3-a81b-01a0e76e4bb3.png)

**Comment by merspieler** [comment]
Those are not for the new model... If you want to contribute liveries, please see the [instructions](https://github.com/legoboyvdlp/A320-family-liveries/blob/master/README.md)
