### ISSUE TITLE
Bug - Incorrect FCU file name capitalization

### ISSUE THREAD

**Issue by colingeniet** [legoboyvdlp/A320-family#27]
**Describe the bug**
File name capitalization `FCU.nas` from https://github.com/legoboyvdlp/A320-family/commit/11431782968684b2f3033a50e03770996b3ebf14 does not match the nasal include
```
<fcu>
	<file>Aircraft/A320-family/Nasal/FMGC/fcu.nas</file>
</fcu>
```
This causes errors on case-sensitive file systems.

**To Reproduce**
Start the aircraft using a case-sensitive file system.

**Comment by legoboyvdlp** [comment]
Should be fixed, pls let me know if not.
