### ISSUE TITLE
Bug: Routeplaner not working

### ISSUE THREAD

**Issue by nicosammito** [legoboyvdlp/A320-family#270]
As seen on the picture, the route planer to automatically plan routes to a specific destination is not clickable.
<img width="1250" alt="Bildschirmfoto 2022-08-15 um 14 27 07" src="https://user-images.githubusercontent.com/60352747/184635028-d2dbf0a0-ab7f-44ca-b0c7-62febf70e06b.png">

**Comment by legoboyvdlp** [comment]
It's not meant to be, sorry - you need to use the MCDU, or it won't work. There's tutorials available on YouTube and you can also download a plan from Simbrief if you insert your username into the dialogue box and then use INIT REQUEST
