### ISSUE TITLE
Bug - flap and speedbrake levers animation

### ISSUE THREAD

**Issue by MariuszXC** [legoboyvdlp/A320-family#271]
**Describe the bug**
Applying flaps with ']' (right square bracket) results in flap lever animation hiding the lever into pedestal.
Identical behaviour applies to speed brake lever, respectively.

**To Reproduce**
Steps to reproduce the behaviour:
1. Keep applying flaps with ']' key
2. Observe flaps lever being animated forward and disappearing into pedestal.
3. Do same test for speedbrake lever (using mouse scroll wheel)
4. Observe the same error in animation (lever disappearing into pedestal).

**Expected behaviour**
Animations moving levers in expected directions.

**Screenshots**
https://ibb.co/ThRtSbR
https://ibb.co/85ZB669
<a href="https://ibb.co/ThRtSbR"><img src="https://i.ibb.co/ThRtSbR/flaps2.jpg" alt="flaps2" border="0"></a> <a href="https://ibb.co/85ZB669"><img src="https://i.ibb.co/85ZB669/flaps0.jpg" alt="flaps0" border="0"></a>

**System (please complete the following information):**
 - OS: Linux, Ubuntu 22.04.1 LTS
 - FlightGear version: 

FlightGear version: 2020.4.0
Revision: 91ddbf6a7c2ada337251bbc4279ef3563538f228
SimGear version: 2020.4.0
OSG version: 3.6.5
PLIB version: 185

 - A320 Version: (FGAddon/Laucher or branch with commit)

3D / 11e8d346

**Additional context**
none

**Comment by SP-NTX** [comment]
that's known issue with nightly

**Comment by legoboyvdlp** [comment]
I do not observe this here. Did you make any changes to your aircraft?

**Comment by legoboyvdlp** [comment]
I see it's something to do with the nightly. I'd be uncomfortable with fixing this because then it will break it for 2020.3 The minimum version is 2020.3.

Also, is it not better for this to be fixed with FlightGear, rather than aircraft adjusting for FlightGear bugs? Have you opened a ticket in Sourceforge?

**Comment by MariuszXC** [comment]
Did not make any changes to the aircraft.
Did not consider it to be an issue with FG, as other planes' animations work as expected.
It could be an issue with this particular animation type / rotation axis specification, though. Are there any pointers to this being discussed as a bug in next?

**Comment by MariuszXC** [comment]
Just had an idea. Could it be, that 'next' interprets the rotation axis as a vector, i.e. beginning and end point of rotation axis matter?
I am not good with Blender, but if someone could modify (reverse direction / rotate by 180 degrees) the flap lever rotation axis I would be happy to test if it fixes the issue better than what I proposed.

**Comment by legoboyvdlp** [comment]
But again, that's going to break the animations for 2020.3, isn't it?

**Comment by MariuszXC** [comment]
It depends. If you create a branch, e.g. 3D/test271, and introduce the change only there, then it will be only visible to those who explicitly check out that branch, so should not affect anyone else.

**Comment by SP-NTX** [comment]
or easier fix, make 3D branch 2020.4 only (the lights will be working, animations will be possible to fix and so on)

**Comment by Octal450** [comment]
Not an issue - this was resolved in the latest next so closing.
-J
