### ISSUE TITLE
Bug - ND canvas don't like ' or ''

### ISSUE THREAD

**Issue by vezza** [legoboyvdlp/A320-family#277]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:
1. Start ND chrono (either CPT of FO)
2. Look at ND chrono 
3. See that ' or '' arem't displayed

**Expected behaviour**
ND Chrono to be displayed with ' and/or '' (example: 01' 25'' or 01 H 36')

**Screenshots**
See attached screenshot

**System (please complete the following information):**
 - OS: Linux Fedora 36 x86_64
 - FlightGear version: Next (Dev)
 - A320 Version: (branch: 3D - commit: 94fba50)

**Additional context**

![Schermata del 2022-11-14 22-44-50](https://user-images.githubusercontent.com/1450066/201777395-c9809699-77f1-4620-9283-28eb6ae2be20.png)

**Comment by merspieler** [comment]
can confirm on nixOS

**Comment by Octal450** [comment]
It was missing in the font.

Fixed.
![image](https://user-images.githubusercontent.com/25598604/201790332-39408b69-6d94-4155-a41a-aace22508bde.png)

Kind Regards,
Josh
