### ISSUE TITLE
Question: can you input airways into the FMGC/SID STAR issue

### ISSUE THREAD

**Issue by alexlenh** [legoboyvdlp/A320-family#280]
I try to input airway J169 towards TFD VOR but i get "NOT ALLOWED", is this function implemented?
![image](https://user-images.githubusercontent.com/46629143/202873064-693e328f-9352-443b-88d2-ceb47a01262f.png)

**Comment by merspieler** [comment]
Not yet.

**Comment by alexlenh** [comment]
Alright, looks like just WPT DCT WPT DCT WPT DCT WPT then

**Comment by merspieler** [comment]
for now, yes

**Comment by alexlenh** [comment]
Also can i drop another question in the same issue

**Comment by merspieler** [comment]
sure, It's just a "question" issue so go ahead

**Comment by alexlenh** [comment]
It might be fg related, but i do install navigraph sids/stars/appr procs properly but at some places only 1 or absolutely no procs show up

**Comment by merspieler** [comment]
to help you with that, we need more information.
which airports? how many procedures are in the files for that airport? do any errors pop up in the flightgear log related to loading the procedures.
There has been a report on the mailing list that in the latest navigraph data there are features which aren't handled by flightgear yet. (iirc the `Between` altitude constraint parameter)

**Comment by alexlenh** [comment]
Airports in question are LYBE (Belgrade Nikola Tesla) and LIRF (Rome), they all have all the procs in 1 file (level-d 767 format), I haven't checked the log yet, and about the no support for ranged altitude constraints (between), does fg just stop loading procs when it first encounters that parameter, like doesn't load rest of the procs

**Comment by merspieler** [comment]
not sure how it behaves as I don't have the data here to check

**Comment by merspieler** [comment]
Well... James just wrote on the mailing list that he's working on fixing the "between" issue... so I'd say wait for the fix then try it with the next/nightly version from after the fix.

**Comment by alexlenh** [comment]
Where will the fix be avail

**Comment by merspieler** [comment]
once available you need either build the next branch your self or use the nightly version available on the build server http://build.flightgear.org:8080/ (idk if there's another more accessible version)

**Comment by alexlenh** [comment]
Maybe the https://download.flightgear.org/builds/nightly/ perhaps

**Comment by merspieler** [comment]
Progress: https://sourceforge.net/p/flightgear/mailman/message/37738898/

**Comment by merspieler** [comment]
> These changes are pushed to next now. So 'between' restrictions in procedures should be handled correctly, and can be detected in Nasal.

James has fixed it...
