### ISSUE TITLE
Airways entry "NOT ALLOWED" when flightplanning in MCDU

### ISSUE THREAD

**Issue by noteas** [legoboyvdlp/A320-family#283]
Dear Contributors of the A320-family Project,

Hi! Recently I have observed a flaw in your model when flying:
![1](https://user-images.githubusercontent.com/116507509/208249582-90c19d63-40f4-4496-98a4-7565988f3c1c.png)
![2](https://user-images.githubusercontent.com/116507509/208249623-34c8b970-602a-47bc-99b0-64bc26af1d07.png)

Maybe this is a feature request instead of bug report.

As is known to all, A320 MCDU flightplanning, in realism, is to enter LEGS -- airways and waypoints.
Real pilots enters a pair of airway and waypoint, one by one after the last SID waypoint, as follow: (captured from FlightFactor A320 for X-Plane11)
![3](https://user-images.githubusercontent.com/116507509/208249990-f82cb077-8529-4652-b27e-6908a76f566e.PNG)
As a result, all the waypoints in the airway will be automatically added, liberating our hands:
![4](https://user-images.githubusercontent.com/116507509/208250118-9ee21263-35be-4bb6-86ad-5495cd66a46e.PNG)

I believe everybody will appreciate it if you fix this soon.

Yours sincerely,
  noteas

 - OS: Windows 10 64-bit
 - FlightGear version: 2020.3.17
 - A320 Version: latest

**Comment by merspieler** [comment]
This is not a bug, it simply hasn't been implemented yet.

**Comment by noteas** [comment]
Could you tell me when will this feature be implemented, please?

**Comment by noteas** [comment]
OK, I see. Thank you very much!

**Comment by noteas** [comment]
With my good technical skills, I will do my best to help you on this problem.

**Comment by merspieler** [comment]
It will come, when it comes.

If you wanna implement this, feel free to fork and open a pull request.
And we're here to help, if you've got questions about it.

**Comment by Octal450** [comment]
The problem is in FlightGear not in the A320 - airway support is not working properly yet. I believe it's been discussed on the mailing list but not corrected yet.

Kind Regards,
Josh

**Comment by noteas** [comment]
Got it. Thank you very much. I will turn to FlightGear developers for help.

**Comment by noteas** [comment]
Fixed in #284. Closed.
