### ISSUE TITLE
Bug - MCDU displays lines when popped out

### ISSUE THREAD

**Issue by FurryMLG** [legoboyvdlp/A320-family#285]
**Describe the bug**
the MCDU displays lines when being popped out

**To Reproduce**
Steps to reproduce the behaviour:
1. Click on MCDU to pop it out
2. See Error

**Expected behaviour**

**Screenshots**
![fgfs-20230113013107](https://user-images.githubusercontent.com/107363918/212216721-1d0c125c-eb7b-4f63-8023-1e3852411ac6.png)

**System (please complete the following information):**
 - OS: Windows 10
 - FlightGear version: 2020.4.0
 - A320 Version: (Latest Repo on Github)

**Comment by merspieler** [comment]
Thanks for reporting this, looks like a wrong canvas ID.... should be an easy fix.
I'll take a look at it when I'm home (if I don't forget)

**Comment by merspieler** [comment]
Can't reproduce here with latest dev branch and 1-2 week old next fg build, looks all fine here,
