### ISSUE TITLE
Bug - Canvas panels disappear when resized

### ISSUE THREAD

**Issue by FurryMLG** [legoboyvdlp/A320-family#290]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:
1. Pop out canvas panels
2. Resize canvas
3. See Error

**Expected behaviour**
Panels Should still work

**Screenshots**
![fgfs-20230207012158](https://user-images.githubusercontent.com/107363918/217124005-49b27609-c240-4e69-94db-81e944b3d161.png)
![fgfs-20230207012054](https://user-images.githubusercontent.com/107363918/217124019-a90a70ba-1004-462f-be6f-d5460533459f.png)

**System (please complete the following information):**
 - OS: Windows 10
 - FlightGear version: 2020.4
 - A320 Version: Lastest Github commit

**Additional Context**
Reloading the aircraft model does NOT work

**Comment by Octal450** [comment]
This is a FlightGear issue.

It's being looked into.

Kind Regards,
Josh
