### ISSUE TITLE
Bug - Remote MCDU shows the PFD

### ISSUE THREAD

**Issue by NichuNaizam** [legoboyvdlp/A320-family#291]
**Describe the bug**
I enabled the remote MCDU and connected via my mobile it shows the altimeter. the buttons work when I press in the phone
it updates in the ingame mcdu.

**To Reproduce**
Steps to reproduce the behaviour:
1. Connect your phone to the remote MCDU
2. Start the plane

**Expected behaviour**
It displays the altitude and speed of the aircraft

**Screenshots**

**System (please complete the following information):**
 - OS: Mac OS Catalina
 - FlightGear version: 2020.3.7
 - A320 Version: FGAddon, latest commit on github

**Additional context**

**Comment by merspieler** [comment]
probably same/similar canvas ID issue as #285

**Comment by Octal450** [comment]
Did we determine why this happened? I remember the ID changes a long time ago but nothing recent.

Josh

**Comment by merspieler** [comment]
no clue, maybe the 3D -> dev merge?

**Comment by NichuNaizam** [comment]
I forgot the screenshot
![Screen Shot 2023-02-08 at 7 45 39 PM](https://user-images.githubusercontent.com/51488611/217682654-6e36848b-6544-4edc-8caf-d67150575da8.png)

**Comment by merspieler** [comment]
Fixed in 51b638

**Comment by NichuNaizam** [comment]
thanks
