### ISSUE TITLE
Bug - Simbrief download failed

### ISSUE THREAD

**Issue by FurryMLG** [legoboyvdlp/A320-family#293]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'MCDU FMGC And INIT'
2. Make sure username is entered into simbrief
3. Click on 'Init Request'

**Expected behaviour**
Import my flight plan

**Screenshots**

**System (please complete the following information):**
 - OS: Win10
 - FlightGear version: latest nightly as of 3/1/23
 - A320 Version: (Latest commit)

**Additional context**
It worked just fine yesterday. I had used the a320 for a week now. I just updated the nightly.

**Comment by legoboyvdlp** [comment]
In 9/10 cases this is because people don't enter the correct username -- due to the switch to Navigraph accounts, you need to enter your 'alias'. As far as I know, it's not case sensitive.

**Comment by FurryMLG** [comment]
yeah I did that. It also seems like around the times it fails, it also fails terrasync. It seems to be just fine now
