### ISSUE TITLE
Bug - When ENG 2 is started first, ENG 2 cutoff valve gets stuck in transition state

### ISSUE THREAD

**Issue by merspieler** [legoboyvdlp/A320-family#296]
**Describe the bug**
From the forum:
https://forum.flightgear.org/viewtopic.php?p=411141#p411141

If ENG 2 gets started first, ENG 2 cutoff valve gets stuck in transition state, if ENG 1 gets started first, this doesn't happen.

**To Reproduce**
( Based off of forum post)
1. Start ENG 2 first,
2. Check fuel page ENG 2 cutoff valve

**Expected behaviour**
ENG 2 cutoff valve fully opens

**Screenshots**
![image](https://user-images.githubusercontent.com/29063255/229288006-57c0854a-af1d-4f69-af6c-e4881a0c8798.png)

**System (please complete the following information):**
(According to forum)
 - OS: Win 10
 - FlightGear version: 2020.3.17
 - A320 Version: latest dev branch

**Comment by Octal450** [comment]
It's an instrumentation problem due to typos, the valve does open properly.

Thank you @merspieler for bringing it to my attention.

Kind Regards,
Josh
