### ISSUE TITLE
Bug - Able to see Apron through PFD & ND

### ISSUE THREAD

**Issue by FurryMLG** [legoboyvdlp/A320-family#299]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:
1. Open FlightGear 2020.4
2. Run A320-Family 
3. Zoom in and see

**Expected behaviour**
Me not seeing it

**Screenshots**
![fgfs-20230409201159](https://user-images.githubusercontent.com/107363918/230794536-4a82a2b7-4940-41a4-b62e-75a84b889ded.png)

**System (please complete the following information):**
 - OS: Windows 10
 - FlightGear version:  2020.4 (latest nightly)
 - A320 Version: "dev" branch from github

**Additional context**
It's a major immersion breaker.

**Comment by Octal450** [comment]
That's weird, I don't have that.

-J

**Comment by L1011H** [comment]
Not observed on my side. This could be related to a texture having an alpha channel. Pull from master if you have messed with the textures or have an outdated version.

**Comment by FurryMLG** [comment]
I just redownloaded and I still have the issue

**Comment by jredpathQUB** [comment]
This looks to me like an issue caused by Compositor, not the A320.

**Comment by FurryMLG** [comment]
Yeah Confirmed Compositor Issue, tried on 777, now with the button Textures goofed.
