### ISSUE TITLE
Feature request: Tiller steering

### ISSUE THREAD

**Issue by merspieler** [legoboyvdlp/A320-family#3]
### General
----

I am submitting a: (select one) 
* [ ] Bug report
* [x] Feature request

### Details
----
#### Current Behavior (if applicable)

Tiller is linked to rudder

#### Requested Behavior  (feature requests)

Default stays the current way but can be seperated to use a seperate axis for the tiller

**Comment by legoboyvdlp** [comment]
Yep.

**Comment by legoboyvdlp** [comment]
REF AMM ATA 32 GEAR (CESA) pp 4822 - 4828
Relationship between input angle and output steering angle:
![image](https://user-images.githubusercontent.com/10434911/82753709-aaea0800-9dbf-11ea-9dc6-2efcd297d789.png)

Deadband on the tiller input:
![image](https://user-images.githubusercontent.com/10434911/82753752-0a481800-9dc0-11ea-88e8-638429c3d601.png)

Relationship to aircraft speed
![image](https://user-images.githubusercontent.com/10434911/82753713-af162580-9dbf-11ea-9c95-441db95d9dd8.png)

Centering when nose gear not compressed; maximum towing angle
![image](https://user-images.githubusercontent.com/10434911/82753707-a6bdea80-9dbf-11ea-81db-acbca3e75767.png)

Steering rate:
![image](https://user-images.githubusercontent.com/10434911/82753907-6eb7a700-9dc1-11ea-8fef-cd81acbb5171.png)

**Comment by legoboyvdlp** [comment]
As to how to implement this: I would suggest:

- Tiller control goes from -1 to 1
- Map this to -75 to 75 
- Use a function to map this input tiller angle to output steering angle (first image)
- Mix this with rudder input (+- 6 degrees) **Not entirely sure how that would work, sum or...?**
- If autopush is connected, use its command; if not use the output of the mixed tiller / rudder. 
- Factor by (75 / 95) = 0.78947 to limit to 75 degrees.
- Autopush can access 95 degrees
- Input this to the nose gear actuator if nose compressed, else zero.
- Actuator depends on the hydraulic power, etc.

This is just an idea and may or may not work... :)

I would suggest that full rudder control of the tiller as well be available at least as an option.

**Comment by Octal450** [comment]
I will experiment with this and see what we can do.

Kind Regards,
Josh
