### ISSUE TITLE
Todo - wingflex

### ISSUE THREAD

**Issue by vezza** [legoboyvdlp/A320-family#30]
**Is your feature request related to a problem or missing feature? Please describe.**
Wingflex animation is missing

**Describe the solution you'd like**
add wingflex animation

**Comment by legoboyvdlp** [comment]
absolutely, the wing is already cut for this

**Comment by vezza** [comment]
Can I try to do this?

**Comment by legoboyvdlp** [comment]
I meant, in the new model.

If you want to make the jsb part that controls the wingflex, would be good.

I think it should be affected by:
- lift of the wing (as lift increases, wing tends to rise) -- this **should** mean that as you pitch up / down it should also bend, I am not sure
- fuel in outer wing tanks
- sharklets - increased bending moment, maybe x1.5

**Comment by vezza** [comment]
Ok... I will follow this guidelines: http://wiki.flightgear.org/Wingflexer
is it ok?

**Comment by legoboyvdlp** [comment]
It's is, yes

**Comment by vezza** [comment]
Ok, I've already done the wingflex of the A350XWB, I hope I'll be able to do a nice work...

**Comment by merspieler** [comment]
Another factor in wingbending is G-load due to turbulences

**Comment by vezza** [comment]
Where is the new 3D model? Someone is working on it? Do we have a forecast on when it will be merged?

**Comment by legoboyvdlp** [comment]
Yes, it's been worked on for about a year now by CaptB, estimated in January.

**Comment by legoboyvdlp** [comment]
Close - wontfix.
