### ISSUE TITLE
Feature Request - Approach vias

### ISSUE THREAD

**Issue by jojo2357** [legoboyvdlp/A320-family#303]
Today I was flying with [these procedures](https://github.com/jojo2357/flightgear-star-sid-manager/blob/b752c4d9f2a7f0a228ddd98f322865ca53fa6742/2020.3/Airports/K/S/F/KSFO.procedures.xml) on ILS28R. I found that the points `EDDYY` and `SIDBY` wouldnt show up, as they are on an approach transition (see [this chart](https://aeronav.faa.gov/d-tpp/2305/00375IL28R.PDF)).

I believe that the currently non-functional `vias` is how I would have been able to select the transition to get those points and restrictions.

**Comment by merspieler** [comment]
I struggle to find those points here... which STAR did you use?

**Comment by jojo2357** [comment]
[KSFO_BSR3.PDF](https://github.com/legoboyvdlp/A320-family/files/14159127/KSFO_BSR3.PDF)
[KSFO_IL28R.PDF](https://github.com/legoboyvdlp/A320-family/files/14159128/KSFO_IL28R.PDF)

These should be roughly correct. I do not really remember what happened, perhaps I should have documented it better.

**Comment by merspieler** [comment]
Um... I'm not sure here what would be the right thing, in terms of procedures (regardless of the FMS behavior)

The last fix on the BSR3 STAR is MENLO, which is already past SIDBY
![screenshot-2024-02-05_18:24:57](https://github.com/legoboyvdlp/A320-family/assets/29063255/4adeb729-09a6-461c-b140-ee933bfdac38)

So idk how one would be able to follow that transition AND the STAR at the same time.
So to me (and also looking at the nav data) it seems the correct thing would be not having a transition here as the STAR makes you already end up on the localizer.
