### ISSUE TITLE
Bug - 

### ISSUE THREAD

**Issue by HarryChaiChai** [legoboyvdlp/A320-family#307]
Not being able to start engines on mac
This is the case for both manual start and auto start

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'aircraft config
2. Click on 'ready to taxi'
3. aircraft goes cold and dark/ n2 falls back to 0 for a manual start

**Expected behaviour**
Engine to start running

**System (please complete the following information):**
 - OS: Mac Big sur 11.7.8
 - FlightGear version: 2020.3.18
 - A320 Version: all

**Additional context**
Sorry if I'm doing anything wrong

**Comment by Octal450** [comment]
There is no bug like this. Make sure the plane is installed correctly 

Kind Regards,
Josh

**Comment by HarryChaiChai** [comment]
Hi, can you please let me know how to install it properly? I honestly know
nothing about coding

Thanks,
Harry
