### ISSUE TITLE
Todo - Brakes temperature

### ISSUE THREAD

**Issue by vezza** [legoboyvdlp/A320-family#31]
**Is your feature request related to a problem or missing feature? Please describe.**
Missing brakes temperature

**Describe the solution you'd like**
- Add Brakes temperature;
- Add brakes fan (remind the panel switch/indicator);
- Add gear damage if temp > max_temp_limit.

**Comment by legoboyvdlp** [comment]
If you want to do some research, I could use any data about carbon brake temperature.

**Comment by vezza** [comment]
Brakes will indicate an amber HOT when the temp is 300° C or more. in the ECAM WHEELS page is shown the brake temp and an arc appears above the hottest brake temp. If brake temp is shown amber above 300° C. The brakes have to be cooled below 300° C before takeoff (Pilots should manually turn on the brake fans)

**Comment by legoboyvdlp** [comment]
yep, but at what rate does temperatue increase proportional to friction applied to brake pad, etc

**Comment by vezza** [comment]
I have a math formula... but for the real data it is hard... to be true I don't know where to find them... is it possible to set some assumed numbers? Then if someone will provide real numbers then it will be easy to fix the assumed one's...

**Comment by legoboyvdlp** [comment]
Yep sure.

**Comment by vezza** [comment]
assumed that kinetic energy is converted in heat during braking as per the following equation

1/2 M V^2 = X Bm T
where:
M=Aircraft Mass
V=Ground Speed
X=brakes heat transfer index
Bm=Brakes mass
T=Braking time

I think it should be possible to calculate brakes temp

**Comment by vezza** [comment]
Otherwise, as a first step, it is possible to adapt the Concorde brakes temp system...

**Comment by vezza** [comment]
The 777 also has a brakes temp system...
