### ISSUE TITLE
Feature Request - Runway Awareness & Advisory System (RAAS)

### ISSUE THREAD

**Issue by Daniel7779X** [legoboyvdlp/A320-family#310]
Implementation of the Runway Awareness & Advisory System (RAAS) for automatic callouts and possibly advisory messages on displays.

The RAAS systems that has already been implemented in the Boeing 777 could possibly be used.

**Comment by SP-NTX** [comment]
This isn't something that would improve realism, and I think this should be a separate addon instead of aircraft thing

**Comment by merspieler** [comment]
Why do you think its not improving realism? While afaik the RAAS isn't by default on the A320 stuff can be retrofitted or as an airline option. Like for example also an update to the ND with airport moving map... not standard but available as an option if airlines want that.
