### ISSUE TITLE
Bug - Engine fatigue?

### ISSUE THREAD

**Issue by DEBUNKED115** [legoboyvdlp/A320-family#311]
So after one fuel stop, I wanted to start flying again but then after taking off the 2nd time, the engine had less power as it did when I first started with a new flight. After the 3rd stop, I thought it might improve after I left it but then the engine became worse and I had a stall even at max throttle.

**To Reproduce**
Steps to reproduce the behaviour:
1. Start a flight and land for a fuel stop
2. Refuel after the engines shut down
3. Once refuelling is complete, restart the engines and get ready for a new flight to anywhere
4. The 2nd or 3rd takeoff after a fuel stop should have a decreased power

**Expected behaviour*
I don't think this should happen even after shutting down everything, but can you explain if I am wrong about it? I may not know about this engine fatigue thing yet

**Screenshots**
No screen shots are available with me

**System (please complete the following information):**
 - OS: MacOS Ventura 13.4.1
 - FlightGear version: 2020.3.17
 - A320 Version: I think it's revision 55 and V1.5.1

**Additional context**
I think this may happen in real life, I think I like the detail if it's supposed to happen, but is there an option or a way to reset all engines to it's default state as it was upon a new startup

**Comment by Octal450** [comment]
No thing like that is simulated. (Or reproducible on my end)

Note that engine performance differs with altitude and outside temperature. Also, weights will affect perceived performance. 

Also, FBW should prevent you from stalling. Can you better describe what happened? Screenshots helpful. 

Kind Regards,
Josh

**Comment by DEBUNKED115** [comment]
Thank you for the reply, unfortunately I have missed the screenshots and since my other flight has ended, I ended up descending to a lower altitude since that's what helps with stall , or just a slightly lower AOA, but after increasing speeds of up to 300 Knots at 20,000 feet, the overspeed and stall limit bar closed together leaving me no choice and I then stalled, I even put on max TOGA throttle, but with no luck, I crash in the desert of east Egypt, my FBW was working with no faults, but probably tried it's best. I was doing a no-passenger flight and the only weights of the aircraft were the total of 380 lbs of both pilots and 43 lbs of bulk cargo, I also took off from Oakland international airport as my first flight, takeoff was successful and normal, but then after the 2nd, things start changing.

**Comment by Octal450** [comment]
Unfortunately without adequate data, I can't really have any insight.
