### ISSUE TITLE
Bug - Texture error in the overhead panel

### ISSUE THREAD

**Issue by DerSpaPhy** [legoboyvdlp/A320-family#312]
Hello!

I have been using and following this project since December 2021 and congratulations on the amazing work you guys are doing, specially the relatively recent graphics overhaul. There is a little error in the overhead panel texture I'd like to remark from my appreciation of the project:
![Captura de pantalla 2023-12-28 021830](https://github.com/legoboyvdlp/A320-family/assets/37450897/57953155-097f-4974-a585-a96797fa34a8)
As it can be seen, the RAT MAN ON guarded switch is a bit displaced and actually clips over the illuminated outline it has. It's not a big deal, but if it gets fixed it would be great. Since it is a texture, I omitted all the info that the template requested, because it is always there so to say, I can gladly provide more details. Keep it up!

**Comment by L1011H** [comment]
This should be a simple fix to the texture, will get to it when I have free moment.

**Comment by DerSpaPhy** [comment]
Also, now that I noticed it, the ELEC PUMP text is also a little bit too close to the green bracket.

**Comment by L1011H** [comment]
> Also, now that I noticed it, the ELEC PUMP text is also a little bit too close to the green bracket.

The files are done in SVG, sometimes when it gets rasterized it will get approximated this way and also due to anti aliasing, will try to make it a bit better, but no guarantees. Changes should be up this weekend.

**Comment by DerSpaPhy** [comment]
Thanks for taking care of it so fast, I might as well mention that the "ENG N1 MODE" text and outlines are missing. In case this is not a bug but just left unfinished, should I open another issue as "feature request"? Please give a low priority to this, I am just contributing little cosmetic details because I can't contribute in other way and enjoy this model a lot, I know there is much more serious work going under the hood.
![Captura de pantalla 2023-12-30 024429](https://github.com/legoboyvdlp/A320-family/assets/37450897/76085623-eb3c-40b7-927d-8146e6b7b589)
![Captura de pantalla 2023-12-30 024511](https://github.com/legoboyvdlp/A320-family/assets/37450897/f6fa54d1-e9a9-429e-8506-50ce53863769)

**Comment by L1011H** [comment]
> Thanks for taking care of it so fast, I might as well mention that the "ENG N1 MODE" text and outlines are missing.  

EDIT:

Ok this is not a texture/model issue, what happens is the following:

Since there are minor overhead differences between the IAE and CFM, there are two switchable panel objects for that area, in this case it seems the appropriate panel object is not swapped with XML logic to accommodate the model chosen.

**Comment by L1011H** [comment]
Fixed slightly displaced OVH decals:RAT MAN ON and ELEC PUMP

**Comment by Octal450** [comment]
Re N1 mode toggles:
I fixed the hide/show logic for IAE vs CFM/PW, so N1 mode switches dont show. The graphical bugs still need to fixed on those switches tho. Once that's fixed, I can make the buttons work.

Kind Regards,
Josh
