### ISSUE TITLE
Feature Request -

### ISSUE THREAD

**Issue by fusspot1** [legoboyvdlp/A320-family#313]
**Is your feature request related to a problem or missing feature? Please describe.**

**Describe the solution you'd like**

**Additional context**
Hi I would like to see a change in the colour around the frames of the instruments to a lighter colour. Now it looks very much like 2D because of a lack of contrast, and it looks very flat. A change of colour will make it look very 3D.

**Comment by Octal450** [comment]
Please fill out the template…

regards,
Josh

**Comment by fusspot1** [comment]
Hi Josh.   I’m very new to GitHub and I don’t know how to to navigate through it.   Obviously is meant for programmers or Linux people.  You asked me to fill in the template.   I wish I knew how to do that.   I was thinking of purchasing a book or two on GitHub published by O’Really but the price is prohibitive.    Thanks mate Sent from my iPhoneOn 30 Dec 2023, at 2:13 pm, Josh Davidson ***@***.***> wrote:﻿
Please fill out the template…
regards,
Josh

**Comment by Octal450** [comment]
Hi,
When you open the issue - it shows the things, which you can replace the text. Those books are not needed, probably only for uploading code or using it with git. Mainly I mean the issue UI.

Anyways, I don't really understand what you mean - if you could copy and paste a screenshot highlighting the issue that would be helpful!

Thanks,
Kind Regards,
Josh

**Comment by fusspot1** [comment]
Sent from my iPhoneOn 30 Dec 2023, at 2:57 pm, Josh Davidson ***@***.***> wrote:﻿
Hi,
When you open the issue - it shows the things, which you can replace the text. Those books are not needed, probably only for uploading code or using it with git. Mainly I mean the issue UI.
Anyways, I don't really understand what you mean - if you could copy and paste a screenshot highlighting the issue that would be helpful!
Thanks,
Kind Regards,
Josh

**Comment by fusspot1** [comment]
Sent from my iPhoneOn 30 Dec 2023, at 2:57 pm, Josh Davidson ***@***.***> wrote:﻿
Hi,
When you open the issue - it shows the things, which you can replace the text. Those books are not needed, probably only for uploading code or using it with git. Mainly I mean the issue UI.
Anyways, I don't really understand what you mean - if you could copy and paste a screenshot highlighting the issue that would be helpful!
Thanks,
Kind Regards,
Josh

**Comment by fusspot1** [comment]
Josh you can see that the FGAddons a320 has less contrast around the frame of the instruments compared with a commercial product.Sent from my iPhoneOn 30 Dec 2023, at 2:57 pm, Josh Davidson ***@***.***> wrote:﻿
Hi,
When you open the issue - it shows the things, which you can replace the text. Those books are not needed, probably only for uploading code or using it with git. Mainly I mean the issue UI.
Anyways, I don't really understand what you mean - if you could copy and paste a screenshot highlighting the issue that would be helpful!
Thanks,
Kind Regards,
Josh

**Comment by L1011H** [comment]
> Josh you can see that the FGAddons a320 has less contrast around the frame of the instruments compared with a commercial product>

Sir, you have asked this exact question on Discord and I have replied. I say again, to have high fidelity graphics you should manually download and install  the dev version from github.
