### ISSUE TITLE
Feature Request - Make the a318, a319 and a321, with NEO version

### ISSUE THREAD

**Issue by ghost** [legoboyvdlp/A320-family#314]
The a320 family should have the a318, a319 and a321 planes. Should have more planes in the a320 fiamily.``

**Comment by SP-NTX** [comment]
A day with useless issues is a senseless day aka OMG when you guys will finally stop making senseless issues and think:tm:

**Comment by SP-NTX** [comment]
Even more senseless when you consider this:
![image](https://github.com/legoboyvdlp/A320-family/assets/72032903/0c4ddeef-6f34-4a31-9142-2795110d021c)

**Comment by Octal450** [comment]
It's planned... thanks...

**Comment by L1011H** [comment]
"Should have" And we should have some considerable donations :)
