### ISSUE TITLE
Feature Request - Add reference to another navdata source

### ISSUE THREAD

**Issue by jojo2357** [legoboyvdlp/A320-family#316]
In the readme, there is reference to [pinto's data](https://github.com/legoboyvdlp/A320-family?tab=readme-ov-file#external-tools) which is fairly out of date. Would it be acceptable to mention my project which also mentions a free, open, and up-to-date navdata source?

My project is [`https://github.com/jojo2357/flightgear-star-sid-manager`](https://github.com/jojo2357/flightgear-star-sid-manager)

**Comment by Octal450** [comment]
Awesome project. Sure.

**Comment by jojo2357** [comment]
uh you spelled my name wrong :grimacing:

**Comment by Octal450** [comment]
Sorry... I fix
Josh
