### ISSUE TITLE
Bug - forgotten object nawglass.sharklet

### ISSUE THREAD

**Issue by vezza** [legoboyvdlp/A320-family#318]
**Describe the bug**
I suppose the object nawglass.sharklet has been forgotten, it should be transparent  and hidden in A320-214 (CFM56-5B4) and A320-232 (IAE V2527-A5)

**To Reproduce**
Steps to reproduce the behaviour:
1. Start FG with A320-214 (CFM56-5B4) and A320-232 (IAE V2527-A5)
2. see the object near the wing tip

**Expected behaviour**
object nawglass.sharklet should be transparent  and hidden when A320-214 (CFM56-5B4) or A320-232 (IAE V2527-A5) are in use

**Screenshots**
see attached screenshots

**System (please complete the following information):**
 - OS: Linux Fedora 39
 - FlightGear version: next
 - A320 Version: next branch

**Additional context**
none
![Schermata del 2024-04-15 21-16-22](https://github.com/legoboyvdlp/A320-family/assets/1450066/aedaf412-4b0d-4c60-b5b2-c3dc8fb350dd)
![Schermata del 2024-04-09 22-52-27](https://github.com/legoboyvdlp/A320-family/assets/1450066/a210f31e-269d-4f9a-b7f2-91824072cf34)
![Schermata del 2024-04-09 22-51-53](https://github.com/legoboyvdlp/A320-family/assets/1450066/72bcb091-9c5a-436d-b785-0b497f978957)

**Comment by Octal450** [comment]
Fixed, thank you. The hide/show needed to be on whether sharklet equipped tho, not model.

Kind Regards,
Josh
