### ISSUE TITLE
Feature Request - a321neo

### ISSUE THREAD

**Issue by brooks95** [legoboyvdlp/A320-family#319]
hello I would like to make a request for an Airbus a321neo I see that several people have already made this request but no relevant feedback. How can I help get this model to arrive quickly enough?
I would like to do everything possible to make the a321neo project come to fruition.

**Comment by Octal450** [comment]
It's in the works, but I cannot give an ETA. Once the 3D modelling is finished by CaptB, I already have several FDM bits ready.

Kind Regards,
Josh
