### ISSUE TITLE
Todo - GPWS + Terrain on ND

### ISSUE THREAD

**Issue by vezza** [legoboyvdlp/A320-family#32]
**Is your feature request related to a problem or missing feature? Please describe.**
GPWS is not complete

**Describe the solution you'd like**
- Add animation to GPWS indicators on the glareshield;
- Add Terrain on ND layer to the ND

**Comment by legoboyvdlp** [comment]
😱

**Comment by vezza** [comment]
See: Feature Request - ND missing features #109
