### ISSUE TITLE
Bug - NAV mode behaves oddly after landing

### ISSUE THREAD

**Issue by linguisticmind** [legoboyvdlp/A320-family#324]
**Describe the bug**
You create a flightplan, fly it and land at the destination airport. Then, within the same session, you create a new flightplan, take off, engage the NAV mode and it behaves oddly.

**To Reproduce**
Steps to reproduce the behaviour:
Recorded a video to show exactly what is happening: https://youtu.be/I2shoi4N5mw
But in a nutshell:
1. Start up the aircraft (e.g. with the "Ready for Takeoff" preset)
2. Create a flightplan
3. Fly the route and land at the destination
4. Without ending the session, INIT a new FROM/TO in the MCDU, and create a new flightplan
5. Take off and try engaging the autopilot in the NAV mode to observe the odd behavior

**Expected behaviour**
NAV mode working after landing, creating a new flightplan, and taking off again&mdash;all within the same session.

**Screenshots**
Recorded a video: https://youtu.be/I2shoi4N5mw

**System (please complete the following information):**
 - OS: Debian Stable (12, Bookworm)
 - FlightGear version: 2020.3.19
 - A320 Version: dev, d7ecd42

**Additional context**
I observed similar unexpected behavior when using DIR in the MCDU to go to an arbitrary waypoint while in flight. The aircraft starts flying in unexpected directions, not following the flightplan.

**Comment by Octal450** [comment]
Use of the ROUTE MANAGER is not supported. I am surprised it's not disabled? I will have to disable it. The issue is due to the route manager does not handle waypoint sequencing properly. So the wrong waypoint is selected.

If you can demonstrate the problem using the MCDU ONLY, then I can reopen the issue.

Kind Regards,
Josh

**Comment by linguisticmind** [comment]
~~@Octal450 Could you give me some pointers as to how to do it through the MCDU? That's what I wanted to do initially, and I tried following this tutorial ([link to the place where he selects a SID](https://www.youtube.com/watch?v=c7UJlJMJdfk&t=7m13s)), but no SIDs appear for me in the MCDU (see screenshot).~~

~~Same is true for approaches and airways. I can't select any of those in the MCDU, but in that tutorial he does.~~

Never mind. I was able to get it to work by installing the navdata from https://github.com/l0k1/fg-navaiddata as explained in the [README](https://github.com/legoboyvdlp/A320-family/blob/dev/README.md#navdata). I only tried https://github.com/jojo2357/flightgear-star-sid-manager before, and it looks like there's only data for a limited number of airports in that repo.

Thanks for your great work!

**Comment by linguisticmind** [comment]
@Octal450 I tried reproducing the problem using the MCDU, and I was able to fly the route for the second time, but the route didn't display properly on the NAV display or in the FlightGear's built-in map. I created a [new issue](https://github.com/legoboyvdlp/A320-family/issues/325) for this.
