### ISSUE TITLE
Bug - loses all electrical systems after takeoff (a320 271N)

### ISSUE THREAD

**Issue by erwan-gg** [legoboyvdlp/A320-family#328]
There is a bug on the current aircraft just after takeoff the plane loses all electrical systems  but the engines remain on.
![fgfs-20240624183442](https://github.com/legoboyvdlp/A320-family/assets/133564150/322ba9e9-cbd2-4562-8eb5-9339837ddc35)

**Comment by Octal450** [comment]
Is this new as of the last update? What happens if you take V2500 or CFM56?

**Comment by erwan-gg** [comment]
On the CFM 56 and IAE this is normal while on the PW there is an electrical fault. And I believe it's since the last update.

**Comment by Octal450** [comment]
Try CFM LEAP please. 

I'll be home in a bit ill check it.

**Comment by Octal450** [comment]
Cannot reproduce.
![image](https://github.com/legoboyvdlp/A320-family/assets/25598604/0c620e5b-e8c1-4b49-ad37-7a9d8db93ecb)

Kind Regards,
Josh

**Comment by erwan-gg** [comment]
The bug occurs when leaving the engines on TOGA at around 4000 ft. On the a320 271N model.

**Comment by Lucasmachado38** [comment]
Takeoff with APU on

**Comment by linguisticmind** [comment]
Same here. Was about to report this myself.

@Octal450 Perhaps this short video will help to demonstrate more clearly: https://youtu.be/AStMloGr-oA

Commit 4fd75f7. Before that works fine.

**Comment by Octal450** [comment]
Reproduced. Thank you for the video. Investingating.

**Comment by Octal450** [comment]
I see what's happening. The higher N2 values of the neo engines causes the electrical system to run the CSD too fast which trips the protection.

I will revise the logic.

Kind Regards,
Josh

**Comment by Octal450** [comment]
Thanks guys. Resolved.

Kind Regards,
Josh
