### ISSUE TITLE
Feature Request - Holding Patterns avaliable

### ISSUE THREAD

**Issue by Lucasmachado38** [legoboyvdlp/A320-family#329]
To avoid using HDG to divert the aircraft if it is too high for landing or a go-around, it would be good if the holding patterns were working.

![image](https://github.com/legoboyvdlp/A320-family/assets/171390391/be9a60aa-810b-4602-9cf3-fbb1b84bb4ee)

**Comment by Octal450** [comment]
Duplicate #292
Yes it's planned. No eta.
