### ISSUE TITLE
Todo - WXR on ND

### ISSUE THREAD

**Issue by vezza** [legoboyvdlp/A320-family#33]
**Is your feature request related to a problem or missing feature? Please describe.**
WXR (weather radar) is missing

**Describe the solution you'd like**
- Add weather radar layer on ND

**Comment by legoboyvdlp** [comment]
oh boy
lol

**Comment by legoboyvdlp** [comment]
See do328

**Comment by vezza** [comment]
See: Feature Request - ND missing features #109
