### ISSUE TITLE
Bug - IAE N1 mode axis remains visible in other engines

### ISSUE THREAD

**Issue by Belegestel** [legoboyvdlp/A320-family#333]
**Describe the bug**
In the A320-271N (PW1127G), a number of lines is visible on the ovehead panel. Apparently, they should only be visible in the IAE variant.

**To Reproduce**
Steps to reproduce the behaviour:
1. Start the A320-271N (PW1127G)
2. Look on the overhead panel

**Expected behaviour**
Lack of the given pair of lines.

**Screenshots**
![obraz](https://github.com/user-attachments/assets/bd9abdf1-ef4d-4c7a-9b1a-d42815fb7830)

**System (please complete the following information):**
 - OS: Win10
 - FlightGear version: 2020.3.19
 - A320 Version: dev, 38c1ad1

**Additional context**
Haven't checked the other variants, it's possible the problem is present in others as well

**Comment by Octal450** [comment]
Those are the axis for the IAE N1 mode switches. I'll fix it.

**Comment by Octal450** [comment]
Fixed by 8e0e55d
