### ISSUE TITLE
TODO - verify CFM56 sounds

### ISSUE THREAD

**Issue by legoboyvdlp** [legoboyvdlp/A320-family#34]
Exterior sounds too quiet.

**Comment by legoboyvdlp** [comment]
CFM sounds in general messed up.
Wingview front.
Missing idle external.

**Comment by mattmaring** [comment]
I'd make sure to also compare the changes I made awhile back. I know I fixed it for Mac, but might have broken windows/linux in the process.

**Comment by legoboyvdlp** [comment]
IAE - no engine start for first part, in rear aspect outside. Eng 2.

**Comment by legoboyvdlp** [comment]
No ldg light switch sound from OFF --> ON. ONly retract --> off

**Comment by legoboyvdlp** [comment]
Pushback --> fixed
Exterior sounds at idle --> fixed. 

Ldg light switch --> port from f16, invalid. 

Start sounds outside --> investigating

**Comment by legoboyvdlp** [comment]
GPWS warnings too quiet?

**Comment by legoboyvdlp** [comment]
Start sounds corrected.
