### ISSUE TITLE
Bug - ND when switched to "Plan" shows your plan lines for a second, then they disappear. To reproduce, enter flight plan, and switch ND to "Plan". OS: windows 10 pro. FG version 2020.4/2024.2. A320 271N (PW) 

### ISSUE THREAD

**Issue by N929Q** [legoboyvdlp/A320-family#347]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**

**Screenshots**

**System (please complete the following information):**
 - OS: 
 - FlightGear version: 
 - A320 Version: (FGAddon/Laucher or branch with commit)

**Additional context**

**Comment by N929Q** [comment]
It appears this is not happening every time the game loads, so could be somewhat of an isolated issue, seems like a once every several loads it will do it.

**Comment by Octal450** [comment]
The launcher version is not the same as here. It's very old (2019).

So I'm closing for now.
