### ISSUE TITLE
Bug - Pitch trim issue when engines are shut down in flight

### ISSUE THREAD

**Issue by linguisticmind** [legoboyvdlp/A320-family#348]
**Describe the bug**
Pitch trim wheel goes to the full up position when the engines are turned off in flight. However, when this happens, the position of the trim wheel doesn't reflect the actual position of the flight control surface.

The pitch trim indication on the lower ECAM display remains constant, stuck at the value it was at prior to the engine shutdown. Moving the trim wheel manually (in alternate or direct law) doesn't affect either the lower ECAM indication, or the plane's flight characteristics.

I recorded a video to demonstrate: https://youtu.be/rCJXwX3fRCY

**To Reproduce**
Steps to reproduce the behaviour:
1. Get airborne
2. Turn off both engine master switches
3. Try to maintain a constant airspeed (I did 220 kt)
4. Watch the trim wheel, and compare its position with the pitch trim indication on the lower ECAM display, and observe the plane's flight characteristics

See demo videos above for details.

**Expected behaviour**
Similar behavior of the pitch trim system that you see if you fly in alternate or direct law with the engines running. E.g. by enabling said control laws in FBW settings.

**System (please complete the following information):**
 - OS: Debian GNU/Linux bookworm 12.7
 - FlightGear version: 2024.2.0
 - A320 Version: GitHub version (b4963a9, latest at the time of posting)

**Additional context**
Also tested on the FGAddon 2020 version of A320. The behavior is exactly the same.

**Comment by linguisticmind** [comment]
@Octal450 [previously said](https://github.com/legoboyvdlp/A320-family/issues/322#issuecomment-2381605192) that it is best to assign him so that he gets notified about an issue, and I believe this is his area of expertise :)

**Comment by linguisticmind** [comment]
Never mind. Figured it out.

https://www.quora.com/If-the-Airbus-A320-lost-power-in-both-engines-but-still-had-THS-would-you-still-have-flaps
https://forums.x-plane.org/index.php?/forums/topic/181934-engines-out-rat-and-apu-bug/#elControls_1677513_menu

With APU, turning on YELLOW ELEC PUMP gets trim control back, and allows to extend the gear normally.

https://www.quora.com/Why-does-the-yellow-hydraulic-pump-on-an-Airbus-320-make-a-twitching-growling-sound-after-a-landing

**Comment by linguisticmind** [comment]
@Octal450, I kind of still wonder if the movement of the pitch trim wheel is erroneous. I understand that with the green and yellow hydraulic systems down, you lose control of the horizontal stabilizer. But if THS is not operational under those condidtions, then why would the pitch trim wheel keep moving? And to the full nose-up position?

See [video](https://youtu.be/rCJXwX3fRCY) to see what I mean.

**Comment by Octal450** [comment]
It is erroneous, you're right.

**Comment by Octal450** [comment]
Fixed.
