### ISSUE TITLE
Bug - NW STRG DISC not amber when ENG running

### ISSUE THREAD

**Issue by merspieler** [legoboyvdlp/A320-family#35]
**Describe the bug**
According to FCOM DSC-32-20-30 P1/2 the `NS STRG DISC` message becomes amber when an an engine is running

**Comment by legoboyvdlp** [comment]
thanks :+1:

this is already implemented?

`if (getprop("/engines/engine[0]/state") == 3 or getprop("/engines/engine[1]/state") == 3) {
		nw_strg_disc.colour = "a";
	} else {
		nw_strg_disc.colour = "g";
	}`

**Comment by merspieler** [comment]
Yep, I've overlooked it... my bad
