### ISSUE TITLE
Remove rendering setting dialog and theme

### ISSUE THREAD

**Issue by merspieler** [legoboyvdlp/A320-family#37]
Due to the recent discussions on the mailing list (PA28 in FGAddon thread) we should remove these as well as the update dialog, before pushing to fgaddon

**Comment by legoboyvdlp** [comment]
Definitely not; I am not going to compromise the user experience to suit those who have nothing better to do with their time than to pull apart others' work.

Sorry, maybe I am too grumpy tonight

The correct solution is as already suggested to add the themes to FGDATA, not needlessly destroy work.

**Comment by merspieler** [comment]
by remove I've just ment from the repo... not in general...

**Comment by merspieler** [comment]
I assume, this can be closed, since it's in fgaddon now
