### ISSUE TITLE
Bug - Endless refueling

### ISSUE THREAD

**Issue by merspieler** [legoboyvdlp/A320-family#39]
**Describe the bug**
In certain cases the refueling doesn't stop (stops when tanks are full).

**To Reproduce**
Steps to reproduce the behaviour:
* A:
  1. Set Requested Fuel Quantity to -10
  2. Klick refuel
  3. Observe endless fueling
* B:
  1. Set Reuqested Fuel Quntity to 10
  2. Klick more than once on refuel (wait until refuel is done before klicking again)

**Expected behaviour**
Refuel only goes to requested fuel level

**Comment by legoboyvdlp** [comment]
Argh!

Ok, thanks. I thought I checked for the negative fuel case.

**Comment by legoboyvdlp** [comment]
Can we accept that the fuel system will overrun by between 0 < n < 9 lbs the requested fuel quantity, due to how the timer controlling the refuel valves works?

**Comment by merspieler** [comment]
I don't think, the real one is that accurate as well...
