### ISSUE TITLE
Bug - APU fire test doesn't sound on battery power

### ISSUE THREAD

**Issue by merspieler** [legoboyvdlp/A320-family#43]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:
1. Start cold and dark
2. Turn on batteries
3. Press APU FIRE TEST btn
4. No waring sound

**Expected behaviour**
Warning should sound

**Comment by legoboyvdlp** [comment]
Thank you, looks like the elec supply is messed up!

**Comment by legoboyvdlp** [comment]
Invalid, no sound without FWC powered.
