### ISSUE TITLE
Bug - APU master and start sw not powered by battery

### ISSUE THREAD

**Issue by merspieler** [legoboyvdlp/A320-family#44]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:
1. Start cold and dark
2. Turn on batteries
3. press APU MASTER and APU START sw
4. No `ON` sign

**Expected behaviour**
The switches show `ON`

**Comment by legoboyvdlp** [comment]
Looking at the manuals for this. I can't find the power source of the lights. Might need to try and find the AMM for the APU, I think I had it noted but not downloaded.

**Comment by legoboyvdlp** [comment]
according to pprune:

> - BAT ONLY in flight, it is NOT possible to Start the APU because the ECB-starter is INOP

> - BAT ONLY on the ground it is POSSIBLE to start the APU (*if speed below 100kts)

**Comment by merspieler** [comment]
I couldn't find anything in the docs. But it has to be either ac-si-ess or dc-bat as these are the only two that are powered at that time.
