### ISSUE TITLE
Bug - FLOOD LT PED doesn't illuminate flap lever scape

### ISSUE THREAD

**Issue by merspieler** [legoboyvdlp/A320-family#46]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:
1. Start at night
2. Turn on the FLOOD LT PED
3. Observer flap lever scale

**Expected behaviour**
Scale gets illuminated as all other markings

**Comment by legoboyvdlp** [comment]
Luckily I found the blender file I thought I lost...

**Comment by legoboyvdlp** [comment]
Looks like its a bug / problem in blender - so I will try and do it in GIMP.
