### ISSUE TITLE
Bug - RAT not working as expected

### ISSUE THREAD

**Issue by vezza** [legoboyvdlp/A320-family#47]
**Describe the bug**
RAT not working as expected:
1) if in "auto" mode it should automatically deploy if airspeed > 100 knots and both AC1 and AC2 are lost/failing;
2) if in "manual" mode it should deploy when yuo open the guard and push the key even in cold and dark cockpit.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to A320 Cockpit (in flight or on the ground)
2. On the ELEC EMER PWR panel open the red guard and click on 'MAN ON'
3. RAT not deploying

**Expected behaviour**
at the above point 3, RAT should deploy

**Screenshots**

** System (please complete the following information):**
 - OS: Linux
 - FlightGear version: 2019.2.0

**Additional context**

**Comment by legoboyvdlp** [comment]
I think I forgot to actually make it deploy the RAT - does the EMER GEN itself turn on?

**Comment by vezza** [comment]
yes, the EMER GEN turns on both in auto and in manual mode... it seems that the property /controls/hydraulic/rat-deployed isn't set to true when EMER GEN gets activated

**Comment by legoboyvdlp** [comment]
Fixed.
