### ISSUE TITLE
Bug - Stall warning while taxiing

### ISSUE THREAD

**Issue by merspieler** [legoboyvdlp/A320-family#52]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:
1. Taxi at 10kn with 15kn wind form behind
2. Do a 90 degree turn to either side
3. Observe Stall warning

**Expected behaviour**
No stall warnings while taxiing

**Comment by legoboyvdlp** [comment]
Best report this to jsbsim, aoa shouldn't be weird on the ground, probably some numerical issues. 
I will increase the value which I adjust the aoa by to avoid this then to 30 knots...
