### ISSUE TITLE
Bug - Warning sounds when switching view

### ISSUE THREAD

**Issue by merspieler** [legoboyvdlp/A320-family#57]
**Describe the bug**

Warnings sound when switching from outside to inside view.

**To Reproduce**
Steps to reproduce the behaviour:
1. Take off
2. Engage A/THR
3. Go to outside view
4. Retard the THR LVR a bit (to trigger THR LIMIT warning)
5. Switch back inside and hear the sound now.
6. Switch forth and back between view.
7. Return THR LVR to CLB detend

**Expected behaviour**
Warning sounds only once or not at all.

**Screenshots**

** System (please complete the following information):**
 - OS:
 - FlightGear version:

**Additional context**

**Comment by legoboyvdlp** [comment]
Huh, shouldn't happen, will check.

**Comment by legoboyvdlp** [comment]
Reproduced, it happens because I inhibited warning sounds in exterior views.

**Comment by legoboyvdlp** [comment]
@merspieler confirm gone? ty

**Comment by merspieler** [comment]
@legoboyvdlp negative, still occures. (also note, that the detend sound is hearable outside)

**Comment by legoboyvdlp** [comment]
Confirmed fixed. Fixing detents now.
