### ISSUE TITLE
Bug - In-flight start crash (Error 0x223)

### ISSUE THREAD

**Issue by vezza** [legoboyvdlp/A320-family#58]
**Describe the bug**
It is not possible to start the aircraft with an in-flight scenario

**To Reproduce**
Steps to reproduce the behaviour:
1. Start FG in an in-flight scenario (example: 6000ft - 190kn - 30nm from an airport runway);
2. See a "Something happened" Red window showing: Error 0x223 

**Expected behaviour**
Start the aircraft with an in-flight scenario

**Screenshots**

** System (please complete the following information):**
 - OS: Linux - Fedora x86_64
 - FlightGear version: 2019.2.0

**Additional context**

**Comment by legoboyvdlp** [comment]
Hi,
This is not a bug. The aircraft does not support in flight start yet.
