### ISSUE TITLE
Feature Request - Save aircraft state between sessions

### ISSUE THREAD

**Issue by merspieler** [legoboyvdlp/A320-family#69]
**Describe the solution you'd like**

Save state of certain things and load them on startup.
List (non-exhaustive):
* Fuel level
* Eng oil level
* Bat charge (accunt for discharge while fg is not running?)

@legoboyvdlp what would be the best way to implement this?

**Additional context**
First step towards #36

**Comment by legoboyvdlp** [comment]
same way as the space shuttle

**Comment by merspieler** [comment]
i took a look at save.nas... looks doable. only difference is, how do we trigger saving on fg exit?
