### ISSUE TITLE
Feature request: set copilot view as default

### ISSUE THREAD

**Issue by merspieler** [legoboyvdlp/A320-family#7]
### General
----

I am submitting a: (select one) 
* [ ] Bug report
* [x] Feature request

### Details
----
#### Requested Behavior  (feature requests)

Add a checkbox to the config to set the default view to the copilot side

**Comment by legoboyvdlp** [comment]
This was troublesome; I can't remember exactly what but there were issues when I tried doing it; I will investigate further.

**Comment by Kasluk24** [comment]
I took care of this issue and I think I have found a solution. Can I just create a pull request and then someone looks over my changes? Or have I to link it somehow to this issue? Sorry for that question but I'm a newbie on GitHub.

**Comment by merspieler** [comment]
Pullrequest is fine, thank you

**Comment by legoboyvdlp** [comment]
Thanks @Kasluk24 !
