### ISSUE TITLE
Feature Request - Dim pop up canvas as well

### ISSUE THREAD

**Issue by merspieler** [legoboyvdlp/A320-family#74]
**Is your feature request related to a problem or missing feature? Please describe.**
When flying at night, the pop up canvas is still at full brightness. This is as well applicable for
remotly displayed ie. in fgqcanvas.

**Describe the solution you'd like**
Dim the canvas it self.

**Additional context**

**Comment by legoboyvdlp** [comment]
Is it even possible to do this?

**Comment by merspieler** [comment]
Does fg support semi transparent areas? If so, just draw a black square over the entire area and modify it's alpha.
I'll take a look at this, if I find the time to do so today.

**Comment by merspieler** [comment]
It kinda works... but there seems to be a bug. As soon as I add the semi transparent area, EVERYTHING becomes transparent so you can look through the popup.

**Comment by legoboyvdlp** [comment]
Ah yeah.
I think same thing happened in shuttle unfortunately.

It's required tho to have it transparent to have dirt effects etc afaik. So maybe we can accept that its transparent? How bad is it?

**Comment by merspieler** [comment]
if I see it right, the more you dim, the more transparent it gets... so full brightness -> ok, no brightness -> fully transparent.

**Comment by legoboyvdlp** [comment]
Anything on this?

**Comment by merspieler** [comment]
No... but it seems to be related to our way of calling our popup windows...

If I pop one of our svg files with semi-transparent dimming layer into the Pipistel Alpha Electro payload dialog, it's not transparent.

So they do something differently.

I didn't look into this much further yet.

**Comment by legoboyvdlp** [comment]
Our popups seem to be standard ones. That's a bit weird.

**Comment by Octal450** [comment]
I will investigate this.
J

**Comment by Octal450** [comment]
This can't be done because it would affect the cockpit's displays also - and since dimming works completely differently there (via light emission) it would be problematic... we'd need to run 2 separate canvas instances which would cause performance concerns with very little gain :/

Kind Regards,
Josh

**Comment by merspieler** [comment]
@Octal450 and what if we keep the emission the same on the 3D cockpit and only dim the canvas?

**Comment by Octal450** [comment]
You can't, changing the canvas in any way would also affect it in the cockpit.

It's a single canvas wrapped by either a Canvas GUI or placed onto a mesh object.

Kind Regards,
Josh

**Comment by merspieler** [comment]
yes, exactly.
change the canvas, don't change the emission -> same effect on the 3D display

**Comment by Octal450** [comment]
It doesn't work - it will look wrong. Right now, the brightness and emission are handled for the display shader to get realistic dimming, which would be lost. You will get a bright dark grey and dusty screen.

The old display shader used to do similar at night, when the screens off if you remember - bright dusty/dark grey screen. So it isn't "dim".

Kind Regards,
Josh

**Comment by merspieler** [comment]
okay, thanks for explaining

**Comment by Octal450** [comment]
Np!
Let me know if you have any other ideas.
-J

**Comment by merspieler** [comment]
iirc you can embed an existing canvas into another one...
could that be used?
so we render the PFD for example as usual, then make a PFD_popup canvas where we just load the already existing canvas and something to dim everything.
yes we increase the number of canvases but wouldn't re-render the entire PFD with all it components.
