### ISSUE TITLE
Feature Request - Missing pfd features

### ISSUE THREAD

**Issue by merspieler** [legoboyvdlp/A320-family#75]
@hayden2000 

Done in this phase:
* ILS warning flash
* Flashing QNH/STD when above/below transition alt/level
* Pulsing alt box, when about to reach selected alt
* V1, VR, V2 indications on PFD
* Fix ILS location
* ILS message stops flashing too early, change trigger property
* Flaps (F and S) speeds
* Max flap speeds
* Green dot speeds

**Comment by legoboyvdlp** [comment]
Thanks hayden 👍 
PFD looking a lot better now - can't wait to see your next features!

**Comment by legoboyvdlp** [comment]
I've changed the timer to double the period - there are some specifics of the altitude alert that probably could be better (e.g. sometimes it flashes amber, sometimes yellow depending on whether you are approaching a selected altitude or deviating from it but currently it appears that it only flashes yellow) but I will improve it later and add a C-Chord sound as well.

I can improve the APPR page also.

**Comment by legoboyvdlp** [comment]
Added elevation feature

Useful resource:
https://www.youtube.com/watch?v=n3TJMro_NzA

**Comment by vezza** [comment]
Added Chronometer indicator: Numbers appear when the onside chronometer is started. They display the elapsed time. The indication is in minutes and seconds from 0 to 59 min 59 s, and in hours and minutes from 1 h to 99 h 59 min (Seconds are not displayed beyond 59 min 59 s).

**Comment by legoboyvdlp** [comment]
Surely this is on ND rather than PFD?

**Comment by vezza** [comment]
Yes sorry... moved to: Feature Request - ND missing features #109

**Comment by mattmaring** [comment]
Rest will be completed with the speed rewrite, closing this now :)

**Comment by legoboyvdlp** [comment]
Great work and many thanks indeed :)
