### ISSUE TITLE
Feature Request - APPR page on MCDU

### ISSUE THREAD

**Issue by mattmaring** [legoboyvdlp/A320-family#78]
Add an APPR phase page to the MCDU under PERF

**Additional context**
Just necessary stuff for pfd such as VAPP, DEST QNH, F, S, O, VLS, etc

**Comment by legoboyvdlp** [comment]
Ok. :+1: 
Thanks!

**Comment by mattmaring** [comment]
Added to pfd branch, I'll connect this at a later time. Closing for now.
