### ISSUE TITLE
Feature Request: Keyboard mode for MCDU

### ISSUE THREAD

**Issue by merspieler** [legoboyvdlp/A320-family#8]
### General
----

I am submitting a: (select one) 
* [ ] Bug report
* [x] Feature request

### Details
----
#### Current Behavior (if applicable)

MCDU entrys only possible by mouse

#### Requested Behavior  (feature requests)

Enter a Keyboard mode where all key strokes go to the MCDU so you can use your keyboard to manipulate the MCDU.  
F1 through F6 for left LSK 1-6  
F7 through F12 for right LSK 1-6

This would make MCDU entries much easier.

**Comment by legoboyvdlp** [comment]
I would need to think how to do this, but good idea in theory.

**Comment by merspieler** [comment]
The [FG1000](http://wiki.flightgear.org/G1000#Multikey_Support) seems to support entering text directly (not tested tho)

**Comment by mattmaring** [comment]
I'll work on this :)

**Comment by mattmaring** [comment]
Is the walker being used? It doesn't seem to be working for me and is causing issues with the MCDU key bindings.

**Comment by legoboyvdlp** [comment]
Yes, it is - use the menu item to spawn a walker outside?

The MCDU key bindings must be toggleable though e.g. if you click the screen, or something so the walker could be disabled if the keyboard mode is active or vice versa?

What are the specific issues?

**Comment by mattmaring** [comment]
Ok, cool

I'm not super familiar with xml, but this is the line giving me trouble:
`<PropertyList include="Aircraft/Generic/Human/Include/walker-include.xml">`

How would temporarily not include that path later in the file?

**Comment by mattmaring** [comment]
I've pushed the my progress to the speed-rewrite branch. The two issues I see:
- walker as described above
- for some reason it has disabled the '/' shortcut to the property browser, calling the gui.property_browser(); doesn't work

How to use:
Enable MCDU mode: shift-n
Disable MCDU mode: shift-m
Letters: lowercase key (I can add uppercase as well, if desired)
.: dot
/: slash
delete (macOS)/backspace (windows): clr
-: plusminus
left/right/up/down: left/right/up/down
(space): sp

**Comment by legoboyvdlp** [comment]
Excellent!

I'll check out the property browser now. As for the walker, I'll need to talk to the mailing list about that I suppose 🤔

**Comment by legoboyvdlp** [comment]
It says : 

"The Keys "a", "A" and "s" have their normal Binding when not in Walk View or Walker Orbit View."

Unfortunately it does that by overriding the default ones.

I'll need to talk to the mailing list.

**Comment by legoboyvdlp** [comment]
Actually - what about copying the keybindings from the referred-to walker-include.xml file, and adding your extra functionality? Doesn't adding your own keybindings _later_ in the -main.xml file override any keybindings added by the -include.xml file?

**Comment by mattmaring** [comment]
Cool, got both the walker and property browser working!

**Comment by mattmaring** [comment]
I've made improvements on the latest push on the speed-rewrite branch:
- Text entry now enabled/disabled based on visibility of MCDU gui dialog
- Independent text entry for left/right MDCU now allowed
- Support for caps lock and shift when entering letters
- Remove key bindings for shift-n/shift-m for enable/disable (to allow the above to work)

**Comment by merspieler** [comment]
um... what for do we neet capitals?... or rather lower case.

**Comment by mattmaring** [comment]
I've been using it for a few weeks and found it kinda weird only having half of the key commands  when in the keyboard mode, especially since it can cause scenarios where you can perform an action but not undo it:

For instance if you accidentally type Shift-v instead of v, you'll be progressed to a different view. To get back to the previous view, you would need to disable keyboard entry mode, press v, then re-enable.

Just got really annoying in my opinion, especially for stuff like the gear when in flight, which you definitely do not want to accidentally trigger.

**Comment by merspieler** [comment]
Yep... makes sense... I was only thinking about contolling the MCDU.
