### ISSUE TITLE
Feature Request - MCDU/PFD Speed Rewrite

### ISSUE THREAD

**Issue by mattmaring** [legoboyvdlp/A320-family#99]
Completely rewrite the speed logic to more accurately model the actual logic:
Fixes issues #8, #75, #78, and #96

MCDU changes:
- INIT: A, IRS INIT, FUELPRED, B
- PERF: TO/CLB/CRZ/DES/APPR/GA
- PROG: TO/CLB/CRZ/DES

FMGC changes:
- APPR logic (done)
- GA logic (done, bugs in unrelated code)
- Rewrite alt logic (done)
- Rewrite speed logic (done)
* [x] Use V1SG to preform all speed calcs, save as variables for various phases in MCDU
* [x] Integrate with FPLN

PFD features:
* [x] Protection speeds
* [x] ILS autoselect when approach is selected
* [x] Radio and baro
* [x] Altitude landing elevation and ground reference DSC 31-40- P 12 + 13 / 32

**Comment by mattmaring** [comment]
@legoboyvdlp, would you like the fuel values in INIT-B to be kg or lbs?

**Comment by legoboyvdlp** [comment]
Lbs please - I need to do KG sometime but I will do it all together.

**Comment by merspieler** [comment]
The idea was to keep the system in lbs and just change the display to KG, if the user wants to

**Comment by mattmaring** [comment]
I have completed most of the speed rewrite. Protection speed bars have also been added along with a bunch of speed/phase/mcdu improvements. Go-around is done and will work properly once the two bugs (alt alert and decel distance) are fixed.

Once I get the current work stable and prepare the SVG files for merging, I'll get started on merging with the flightplan.
![Screen Shot 2020-04-12 at 1 30 57 PM](https://user-images.githubusercontent.com/56924612/79076396-ceea0200-7cc7-11ea-9378-df950bf9c461.png)

**Comment by legoboyvdlp** [comment]
Nasal runtime error: undefined symbol: clean
 1120.01 [ALRT]:nasal        at C:/Users/redpa/Documents/FlightGear/Custom Aircraft/A320-family/Models/Instruments/PFD/PFD.nas, line 1265
 1120.02 [ALRT]:nasal        called from: C:/Users/redpa/Documents/FlightGear/Custom Aircraft/A320-family/Models/Instruments/PFD/PFD.nas, line 299
 1120.02 [ALRT]:nasal        called from: C:/Users/redpa/Documents/FlightGear/Custom Aircraft/A320-family/Models/Instruments/PFD/PFD.nas, line 2683

**Comment by mattmaring** [comment]
I plan on focusing on improving what I have already completed, new stuff will come another day
